objects/Account_Details_by_Show__c.object
<CustomObject>
    <description>Top level object to group Account Segment, Account Detail (External), Account Reg Demo, Product Categories, and Business Categories for a particular account and show.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Details by Shows</relationshipLabel>
        <relationshipName>Account_Details_by_Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Account Details by Shows</relationshipLabel>
        <relationshipName>Account_Details_by_Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Details by Show</label>
    <nameField>
        <displayFormat>ADS-{0}</displayFormat>
        <label>Account Details by Show Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Details by Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EE_AccountDetailsbyShowTriggerTest.cls
@isTest
public class EE_AccountDetailsbyShowTriggerTest {
    static testmethod void EE_AccountDetailsbyShowTriggerTest() {
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;
        
        //Create Show 
        Show__c show = new Show__c();
        show.Name='Test Show';
        show.Brand__c='TBrand';
        show.Market__c='TMarket';
        show.Rule_Set__c='ASD_SB';
        show.Segment__c='TSegment';
        show.Show_Code__c='TShowCode';      
        show.Show_Group__c='ShowGroup';
        show.ShowID__c=12345;
        insert show;

        //Create Account Details by Show
        Account_Details_by_Show__c ads = new Account_Details_by_Show__c();
        ads.Account__c =account.id;
        ads.Show__c = show.id;
        insert ads;
        
        test.startTest();

        try{
            Account_Details_by_Show__c ads1 = new Account_Details_by_Show__c();
            ads1.Account__c =account.id;
            ads1.Show__c = show.id;
            insert ads1;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Account Details by Show Record already exists')? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        
        test.stopTest();

    }
}