objects/Account_Details_by_Show__c.object
<CustomObject>
    <description>Top level object to group Account Segment, Account Detail (External), Account Reg Demo, Product Categories, and Business Categories for a particular account and show.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Details by Shows</relationshipLabel>
        <relationshipName>Account_Details_by_Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Account Details by Shows</relationshipLabel>
        <relationshipName>Account_Details_by_Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Details by Show</label>
    <nameField>
        <displayFormat>ADS-{0}</displayFormat>
        <label>Account Details by Show Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Details by Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Segment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Details_by_Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Details by Show</label>
        <referenceTo>Account_Details_by_Show__c</referenceTo>
        <relationshipLabel>Account Segments</relationshipLabel>
        <relationshipName>Account_Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Segments</relationshipLabel>
        <relationshipName>Account_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Account Segments</relationshipLabel>
        <relationshipName>Account_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Segment__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Account Segment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Winback</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Current Exhibitor</fullName>
                </value>
                <value>
                    <fullName>Current Attendee</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Persona</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EE_CreateAccDetailsbyShowTest.cls
@isTest
public class EE_CreateAccDetailsbyShowTest {

    static testmethod void EE_CreateAccDetailsbyShowTest() {
        date myDate = date.today();
        Date newDate = mydate.addDays(2);
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;

        //Account
        Account account1 = new Account();
        account1.Name='Test Account1';
        insert account1; 

        //Create Show 
		Show__c show = new Show__c();
		show.Name='Test Show';
		show.Brand__c='TBrand';
		show.Market__c='TMarket';
		show.Rule_Set__c='ASD_SB';
		show.Segment__c='TSegment';
		show.Show_Code__c='TShowCode';      
		show.Show_Group__c='ShowGroup';
		show.ShowID__c=12345;
        insert show;
        
        //create Segment
        Segment__c segment = new Segment__c();
        segment.Name ='Test segment';
        segment.Show__c = show.id;
        segment.Type__c = 'Renewal';
        insert segment;

        //create Segment
        Segment__c segment1 = new Segment__c();
        segment1.Name ='Test segment1';
        segment1.Show__c = show.id;
        segment1.Type__c = 'Renewal';
        insert segment1;

        //Create Account details by Show
        Account_Details_by_Show__c ads = new Account_Details_by_Show__c();
        ads.Account__c =account1.id;
        ads.Show__c = show.id;
        insert ads;

        //Create Account Segment
        Account_Segment__c accseg = new Account_Segment__c();
        accseg.Account__c= account.id;
        accseg.Segment__c= segment.id;

        //Create Account Segment
        Account_Segment__c accseg1 = new Account_Segment__c();
        accseg1.Account__c= account1.id;
        accseg1.Segment__c= segment1.id;


        test.startTest();
        insert accseg;
        insert accseg1;
        test.stopTest();
    }
}