objects/AccountOwners__c.object
<CustomObject>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pavilion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pavilion</label>
        <referenceTo>Pavilion__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>Account_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>Account_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubShow</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubShow__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Owner</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>AccountOwnerByShow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Booth_Revenue__c</fullName>
        <label>Target Booth Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AccountNameFirstChar__c</fullName>
        <formula>IF(
    BEGINS(upper(Account.Name), "THE "),
    Upper(RIGHT(LEFT(Account.Name,5),1)),
    Upper(LEFT(Account.Name,1))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountNameFirstChar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryandStateCode__c</fullName>
        <formula>TEXT(Account.BillingCountryCode)+'-'+ TEXT(Account.BillingStateCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BillingCountryandStateCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(Account.BillingCountryCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(Account.BillingStateCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing State Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pavilion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pavilion</label>
        <referenceTo>Pavilion__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <formula>BLANKVALUE(SubExpo__r.SubShow__r.Rule_Set__c,Event__r.Show__r.Rule_Set__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rule Set</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Should_Ignore_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Should Ignore Assignment Rule?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowObjectID__c</fullName>
        <formula>Event__r.Show__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ShowObjectID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpoObjectID__c</fullName>
        <formula>SubExpo__r.Show__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubExpoObjectID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubExpo__c.Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <formula>SubExpo__r.SubShow__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShow</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pavilion__c.object
<CustomObject>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Pavilions</relationshipLabel>
        <relationshipName>Pavilions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pavilion</label>
    <nameField>
        <label>Pavilion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pavilions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubExpo__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubShowName__c</fullName>
        <formula>SubShow__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShowName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubShow</label>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Booth_Revenue__c</fullName>
        <label>Target Booth Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>SubExpo</label>
    <nameField>
        <label>SubExpo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubExpos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubShow__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>SubShows</relationshipLabel>
        <relationshipName>SubShows</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SubShow</label>
    <nameField>
        <label>SubShow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubShows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Rule__c.object
<CustomObject>
    <fields>
        <fullName>IsActiveUser__c</fullName>
        <formula>OpportunityOwner__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsActiveUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key1__c</fullName>
        <label>Key 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key2__c</fullName>
        <label>Key 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Territory_Rule_ID__c &amp; ' - ' &amp; OpportunityOwner__r.FirstName &amp;' ' &amp;  OpportunityOwner__r.LastName &amp; ' - ' &amp;  Key1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Rule_ID__c</fullName>
        <label>Territory Rule ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Rule_Type__c</fullName>
        <label>Territory Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Name</fullName>
                </value>
                <value>
                    <fullName>Billing State</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>SubShow</fullName>
                </value>
                <value>
                    <fullName>Account Name &amp; Billing State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory Rule</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_DefaultOpportunityOwner.cls
public class EE_DefaultOpportunityOwner {
    public static void DefaultOpportunityOwner(Set<ID> oppIds){
        String RT_AccountName = EE_UtilityValues.RT_AccountName;
        String RT_BillingState = EE_UtilityValues.RT_BillingState;
        String RT_Show = EE_UtilityValues.RT_Show;
        String RT_SubShow = EE_UtilityValues.RT_SubShow;
        String RT_ANBS = EE_UtilityValues.RT_ANBS;
        String International = EE_UtilityValues.International;
        String Country_US = EE_UtilityValues.Country_US;

        List<Opportunity> lstOppsToBeUpdated = new List<Opportunity>();
        Set<id> oPPIDSet = new Set<id>();
		
        
        List<Opportunity> oppList = new List<Opportunity>([Select Id,Should_Ignore_Assignment_Rule__c, Event__r.Show__c, Event__r.Show__r.Name, Event__r.Show__r.OwnerId, subexpo__r.subshow__r.rule_set__c, AccountID, AccountNameFirstChar__c, OwnerId,Show__c,SubExpo__r.SubShowName__c, BillingCountryandStateCode__c, Billing_Country_Code__c,Billing_State_Code__c,Rule_Set__c, 
                                                            SubExpo__r.Target_Booth_Revenue__c,SubExpo__r.Name, SubExpo__r.SubShow__c, SubExpo__r.SubShow__r.Name,SubExpo__r.Stage_Date__c,ShowObjectid__c,SubExpoObjectID__c,Pavilion__c
                                                            from Opportunity where Id IN :oppIds 
                                                            and Should_Ignore_Assignment_Rule__c = FALSE
                                                            and Rule_Set__c !='Disabled'
                                                            and Rule_Set__c != NULL
                                                            and Rule_Set__c != ''
                                                            ]);  
    
            //Set<String> TerritoryRulesSet = new Set<String>();
			Set<Id> AccountIds = new Set<Id>();
			Set<Id> ShowIds = new Set<Id>();
            for(opportunity op : oppList) {
                //TerritoryRulesSet.add(op.Rule_Set__c);
				AccountIds.add(op.AccountID);
				ShowIds.add(op.Event__r.Show__c);
            }
			//Account Owner
			List<AccountOwners__c> accOwnersList = new List<AccountOwners__c>([Select AccountOwner__c, AccountOwner__r.IsActive, Show__c, Account__c,SubShow__c,SubExpo__c,Pavilion__c from AccountOwners__c where Account__c IN:AccountIds and Show__c IN: ShowIds and AccountOwner__r.IsActive = TRUE]);
			List<Opportunity> updateOppwithAOList = new List<Opportunity>();
			Set<Id> UpdatedOppIds = new Set<Id>();
            
			if(accOwnersList.Size()>0){
				for(Opportunity opp: oppList){
					for(AccountOwners__c ao:accOwnersList){
                        system.debug('Account Owner Account' + ao.Account__c);
                        system.debug('Opp Account' + opp.AccountID);
                        system.debug('Account Owner Show' + ao.Show__c );
                        system.debug('Opp Show' + opp.Event__r.Show__c);
                        system.debug('ao.SubShow__c'+ ao.SubShow__c);
						if(ao.Account__c == opp.AccountID && ao.Show__c == opp.Event__r.Show__c && ao.SubShow__c == Null && opp.SubExpo__r.SubShow__c == Null ){
							Opportunity UpdateOpp = new Opportunity();
							UpdateOpp.Id = opp.Id;
							UpdateOpp.OwnerId = ao.AccountOwner__c;
							updateOppwithAOList.add(UpdateOpp);
							UpdatedOppIds.add(UpdateOpp.Id);
						}
						if(ao.Account__c == opp.AccountID && ao.Show__c == opp.Event__r.Show__c && ao.SubShow__c != Null && ao.SubShow__c == opp.SubExpo__r.SubShow__c){
							Opportunity UpdateOpp1 = new Opportunity();
							UpdateOpp1.Id = opp.Id;
							UpdateOpp1.OwnerId = ao.AccountOwner__c;
							updateOppwithAOList.add(UpdateOpp1);
							UpdatedOppIds.add(UpdateOpp1.Id);
						}
		
					}
				}
				if(updateOppwithAOList.Size()>0){
					update updateOppwithAOList;
				}
			}
		
			//
			
			List<Opportunity> oppList2 = new List<Opportunity>([Select Id,Should_Ignore_Assignment_Rule__c, Event__r.Show__c, Event__r.Show__r.Name, Event__r.Show__r.OwnerId, Event__r.Show__r.Owner.IsActive, subexpo__r.subshow__r.rule_set__c, AccountID, AccountNameFirstChar__c, OwnerId,Show__c,SubExpo__r.SubShowName__c, BillingCountryandStateCode__c, Billing_Country_Code__c,Billing_State_Code__c,Rule_Set__c, 
                                                            SubExpo__r.Target_Booth_Revenue__c,SubExpo__r.Name, SubExpo__r.SubShow__c, SubExpo__r.SubShow__r.Name,SubExpo__r.Stage_Date__c,ShowObjectid__c,SubExpoObjectID__c,Pavilion__c
                                                            from Opportunity where Id IN :oppIds and Id Not IN: UpdatedOppIds
                                                            and Should_Ignore_Assignment_Rule__c = FALSE
                                                            and Rule_Set__c !='Disabled'
                                                            and Rule_Set__c != NULL
                                                            and Rule_Set__c != ''
                                                            ]);  
    
            Set<String> TerritoryRulesSet = new Set<String>();
            for(opportunity op : oppList2) {
                TerritoryRulesSet.add(op.Rule_Set__c);
			}
			
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:TerritoryRulesSet = ' + TerritoryRulesSet);             
            
            List<Territory_Rule__c> TerritoryRules  = new List<Territory_Rule__c>([Select Name__c,Key1__c,Key2__c, OpportunityOwner__c,Rule_Set__c,Territory_Rule_Type__c, Territory_Rule_ID__c from Territory_Rule__c where Rule_Set__c IN: TerritoryRulesSet and IsActiveUser__c = TRUE order by Name__c ASC]);
            
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:found rules = ' + TerritoryRules);
            
            for(Opportunity oPP : oppList2) {
                
                if(oPPIDSet.contains(oPP.id))
                    continue;
                if(TerritoryRules.size() >0){
                    for(Territory_Rule__c tr: TerritoryRules){
                        if(oPPIDSet.contains(oPP.id))
                            continue;
                            //Account Name
                            if(oPP.Rule_Set__c == tr.Rule_Set__c){   
                                if(tr.Territory_Rule_Type__c == RT_AccountName ){
                                    if(tr.Key1__c.contains(oPP.AccountNameFirstChar__c) ){                             
                                        oPP.OwnerId=tr.OpportunityOwner__c;
                                        lstOppsToBeUpdated.add(oPP);
                                        oPPIDSet.add(oPP.id);
                                        System.debug('@@@@@@@@@@@@@@@@@@@@@' +oPP);
                                        continue;
                                    }
                                }     
                            }
                            
                            //Billing State
                            if(tr.Territory_Rule_Type__c == RT_BillingState){
                                if(String.IsNotBlank(tr.Key1__c) && tr.Key1__c.contains(oPP.Billing_Country_Code__c)){
                                    if(tr.Key2__c=='*') {
                                    // Territory Rules is for the entire country
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@11111' +oPP);
                                    continue;
                                    
                                    } else if ( tr.Key2__c.contains(oPP.Billing_State_Code__c)) {
                                    //Country and State match territory rule
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@2222222' +oPP);
                                    continue;
                                    }
                                } 
                                system.debug('############'+oPP.Billing_Country_Code__c);
                                system.debug('44444444444444'+tr.Key2__c);
                                if(tr.Key1__c== International  && String.IsNotBlank(tr.Key2__c) && oPP.Billing_Country_Code__c != 'NULL' && !tr.Key2__c.contains(oPP.Billing_Country_Code__c) && oPP.Billing_Country_Code__c!= Country_US) {
                                    //International rules except US and whatever countries listed in Key2__c.
                                    //Some times show don't consider Canada as part of international countries                 
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@333333' +oPP);
                                    continue;                                            
                                }
                            }
                    
                            //Show
                            if(tr.Territory_Rule_Type__c == RT_Show && tr.Key1__c.contains(oPP.Event__r.Show__r.Name)){
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);
                                System.debug('@@@@@@@@@@@@@@@@@@@@@44444444444444' +oPP);
                                continue;                                            
                            }
                    
                            //Sub Show
                            if(tr.Territory_Rule_Type__c == RT_SubShow && oPP.SubExpo__r.SubShowName__c != null && tr.Key2__c.contains(oPP.SubExpo__r.SubShowName__c)){
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);
                                System.debug('@@@@@@@@@@@@@@@@@@@@@5555' +oPP);
                                continue;                                            
                            }
                            system.debug('@@@@@@@@@@@@@@@@@oPP.BillingCountryandStateCode__c'+oPP.BillingCountryandStateCode__c);
                            //Account Name and Billing State
                            if(tr.Territory_Rule_Type__c == RT_ANBS && tr.Key1__c.contains(oPP.AccountNameFirstChar__c) && !string.isBlank(oPP.BillingCountryandStateCode__c) && tr.Key2__c.contains(oPP.BillingCountryandStateCode__c)){ 
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);

                                System.debug('@@@@@@@@@@@@@@@@@@@@@66666' +oPP);
                                continue;                                            
                            }                   
                    }
                }

                if(TerritoryRules.size() == 0 || !oPPIDSet.contains(oPP.id)){
                    if(oPP.Event__r.Show__r.Owner.IsActive == True){
                        oPP.OwnerId = oPP.Event__r.Show__r.OwnerId;
                        lstOppsToBeUpdated.add(oPP);
                        oPPIDSet.add(oPP.id); 
                    }
                }
            }
            //Update Opportunity with udpated owner

            
            update lstOppsToBeUpdated;
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:lstOppsToBeUpdated = '+lstOppsToBeUpdated);
    }
}