objects/AccountOwners__c.object
<CustomObject>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubShow</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubShow__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Owner</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>AccountOwnerByShow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubShow</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubShow__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubShow__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>SubShows</relationshipLabel>
        <relationshipName>SubShows</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SubShow</label>
    <nameField>
        <label>SubShow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubShows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_ShowAccountOwnersTgrTest.cls
@isTest
public class EE_ShowAccountOwnersTgrTest {
    static testmethod void EE_ShowAccountOwnersTgrTest(){
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;
        
        //Create Show 
        Show__c show = new Show__c();
        show.Name='Test Show';
        show.Brand__c='TBrand';
        show.Market__c='TMarket';
        show.Rule_Set__c='ASD_SB';
        show.Segment__c='TSegment';
        show.Show_Code__c='TShowCode';      
        show.Show_Group__c='ShowGroup';
        show.ShowID__c=12345;
        insert show;

        //Create Sub Show
        SubShow__c subshow = new SubShow__c();
        subshow.Name = 'subshow';
        subshow.Show__c=show.id; 
        insert subshow;
        
        //User
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'stest', 
                        Email='testuser@testorg.com', 
                        EmailEncodingKey='UTF-8', 
                        FirstName='s',
                        LastName='Test',  
                        LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', 
                        ProfileId = p.Id, 
                        TimeZoneSidKey='America/Los_Angeles', 
                        UserName='testuser@testorg.com');
    
       
        AccountOwners__c AO = new AccountOwners__c();
        AO.Account__c = account.Id;
        AO.AccountOwner__c = u.Id;
        AO.Show__c = show.Id;
        AO.SubShow__c = subshow.Id;
        Insert AO;

        AccountOwners__c AO2 = new AccountOwners__c();
        AO2.Account__c = account.Id;
        AO2.AccountOwner__c = u.Id;
        AO2.Show__c = show.Id;
        Insert AO2;

        test.startTest();

        try{
            AccountOwners__c AO1 = new AccountOwners__c();
            AO1.Account__c = account.Id;
            AO1.AccountOwner__c = u.Id;
            AO1.Show__c = show.Id;
            AO1.SubShow__c = subshow.Id;
            Insert AO1;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Show Account Owner Record already exists for the selected show and subshow combination')? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }

        try{
            AccountOwners__c AO3 = new AccountOwners__c();
            AO3.Account__c = account.Id;
            AO3.AccountOwner__c = u.Id;
            AO3.Show__c = show.Id;
            Insert AO3;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Show Account Owner Record already exists for the selected show')? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        test.stopTest();

        
    }
}