objects/AccountOwners__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>Account_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubShow</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubShow__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipLabel>Account Owners</relationshipLabel>
        <relationshipName>AccountOwnerByShows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Owner</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>AccountOwnerByShow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Booth_Revenue__c</fullName>
        <label>Target Booth Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AccountNameFirstChar__c</fullName>
        <formula>IF(
    BEGINS(upper(Account.Name), "THE "),
    Upper(RIGHT(LEFT(Account.Name,5),1)),
    Upper(LEFT(Account.Name,1))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountNameFirstChar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryandStateCode__c</fullName>
        <formula>TEXT(Account.BillingCountryCode)+'-'+ TEXT(Account.BillingStateCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BillingCountryandStateCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(Account.BillingCountryCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(Account.BillingStateCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing State Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <formula>BLANKVALUE(SubExpo__r.SubShow__r.Rule_Set__c,Event__r.Show__r.Rule_Set__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rule Set</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Should_Ignore_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Should Ignore Assignment Rule?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubExpo__c.Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <formula>SubExpo__r.SubShow__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShow</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityContactRole.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <formula>CASESAFEID( Opportunity.Event__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Pavilion__c.object
<CustomObject>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Pavilions</relationshipLabel>
        <relationshipName>Pavilions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pavilion</label>
    <nameField>
        <label>Pavilion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pavilions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Show_Account_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles by Show</relationshipLabel>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ContactRoles__c</fullName>
        <label>Contact Roles</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A2Z Invoice Contact</fullName>
                </value>
                <value>
                    <fullName>Advertising contact</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Contract Contact</fullName>
                    <default>true</default>
                    <label>Contract Contact</label>
                </value>
                <value>
                    <fullName>Contract Contact (Secondary)</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Decorator</fullName>
                </value>
                <value>
                    <fullName>Directory contact</fullName>
                </value>
                <value>
                    <fullName>Distributor Representative</fullName>
                </value>
                <value>
                    <fullName>Exhibitor kit recipient</fullName>
                </value>
                <value>
                    <fullName>Marketing Contact</fullName>
                </value>
                <value>
                    <fullName>Only contact</fullName>
                </value>
                <value>
                    <fullName>Onsite contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Sponsorship contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles by Show</relationshipLabel>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role by Show</label>
    <nameField>
        <displayFormat>S{0000}</displayFormat>
        <label>Show Account Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles by Show</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SubExpo__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShowName__c</fullName>
        <formula>SubShow__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShowName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubShow</label>
        <referenceTo>SubShow__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubExpo</label>
    <nameField>
        <label>SubExpo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubExpos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubShow__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>SubShows</relationshipLabel>
        <relationshipName>SubShows</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SubShow</label>
    <nameField>
        <label>SubShow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubShows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Territory_Rule_ID__c &amp; ' - ' &amp; OpportunityOwner__r.FirstName &amp;' ' &amp;  OpportunityOwner__r.LastName &amp; ' - ' &amp;  Key1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Territory Rule</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_OpportunityTgr.cls
public without sharing class  EE_OpportunityTgr {  
     
    // Assign Opportunity Owner based on Named Account,Account Owner and Territory Rules.
        //Last Updated by Grant Ongstad 11/15/17
        //Line 23 added subshow ruleset to the query
        //Line 44 Added condition that checks for blank subshow rule set
        
        // 06/12/19 Spoorthy Teegala - addContactRoleByShow - This method is used for adding/creating 
        // Opportunity Contact Roles from Contact Role by Show recrds from associated Account for a given opporunity
    /*public void addContactRoleByShow(Map<id,Opportunity> newOppMap){
        
        List<Opportunity> oppList = new List<Opportunity>();
        Set<Id> AccIdSet = new Set<Id>();
        Map<Id, Opportunity> oppAccMap = new Map<Id, Opportunity>();
        List<Show_Account_Contact__c> CRBSList = new List<Show_Account_Contact__c>();
        List<OpportunityContactRole>  OppCRList = new List<OpportunityContactRole>();
        
        oppList = [Select Id, AccountID,Event__r.Show__r.Name from Opportunity where Id IN :newOppMap.keySet()];
        
        for(Opportunity opp :oppList ){
                oppAccMap.put(opp.ID, opp); 
                AccIdSet.add(opp.AccountID);      
        }
        
        List<String> ValidCRbyShowList = new List<String>{'A2Z Invoice Contact', 'Contract Contact', 'Marketing Contact', 'Sales Contact','Contract Contact (Secondary)', 'Sponsorship contact'};
        CRBSList = [select id, Account__c, Contact__c, ContactRoles__c,Show__r.Name from Show_Account_Contact__c where Account__c IN: AccIdSet and ContactRoles__c IN: ValidCRbyShowList]; 
        
        if(CRBSList.size() > 0){
            for(id OppId: oppAccMap.keyset()) {
                for(Show_Account_Contact__c crbs: CRBSList ){
                    if(crbs.Account__c == oppAccMap.get(OppId).AccountID && crbs.Show__r.Name == oppAccMap.get(OppId).Event__r.Show__r.Name) {
                        OpportunityContactRole ocr= new OpportunityContactRole();
                        ocr.ContactId = crbs.Contact__c;
                        ocr.OpportunityId = OppId;
                        ocr.Role = crbs.ContactRoles__c;
                        OppCRList.add(ocr);
                    }
                }
            }
            
            insert OppCRList;
        }
    }
    
         
    //@future
    public static void updateAccounExecutiveOwner(Set<ID> oppIds){
        String RT_AccountName = EE_UtilityValues.RT_AccountName;
        String RT_BillingState = EE_UtilityValues.RT_BillingState;
        String RT_Show = EE_UtilityValues.RT_Show;
        String RT_SubShow = EE_UtilityValues.RT_SubShow;
        String RT_ANBS = EE_UtilityValues.RT_ANBS;
        String International = EE_UtilityValues.International;
        String Country_US = EE_UtilityValues.Country_US;

        List<Opportunity> lstOppsToBeUpdated = new List<Opportunity>();
        Set<id> oPPIDSet = new Set<id>();
        
        
        List<Opportunity> oppList = new List<Opportunity>([Select Id,Should_Ignore_Assignment_Rule__c, Event__r.Show__c, Event__r.Show__r.Name, Event__r.Show__r.OwnerId, subexpo__r.subshow__r.rule_set__c, AccountID, AccountNameFirstChar__c, OwnerId,Show__c,SubExpo__r.SubShowName__c, BillingCountryandStateCode__c, Billing_Country_Code__c,Billing_State_Code__c,Rule_Set__c, 
                                                            SubExpo__r.Target_Booth_Revenue__c,SubExpo__r.Name, SubExpo__r.SubShow__c, SubExpo__r.SubShow__r.Name,SubExpo__r.Stage_Date__c,ShowObjectid__c,SubExpoObjectID__c,Pavilion__c
                                                            from Opportunity where Id IN :oppIds 
                                                            and Should_Ignore_Assignment_Rule__c = FALSE
                                                            and Rule_Set__c !='Disabled'
                                                            and Rule_Set__c != NULL
                                                            and Rule_Set__c != ''
                                                            ]);  
    
            //Set<String> TerritoryRulesSet = new Set<String>();
            Set<Id> AccountIds = new Set<Id>();
            Set<Id> ShowIds = new Set<Id>();
            for(opportunity op : oppList) {
                //TerritoryRulesSet.add(op.Rule_Set__c);
                AccountIds.add(op.AccountID);
                ShowIds.add(op.Event__r.Show__c);
            }
            //Account Owner
            List<AccountOwners__c> accOwnersList = new List<AccountOwners__c>([Select AccountOwner__c,Show__c, Account__c,SubShow__c,SubExpo__c,Pavilion__c from AccountOwners__c where Account__c IN:AccountIds and Show__c IN: ShowIds]);
            List<Opportunity> updateOppwithAOList = new List<Opportunity>();
            Set<Id> UpdatedOppIds = new Set<Id>();
            
            if(accOwnersList.Size()>0){
                for(Opportunity opp: oppList){
                    for(AccountOwners__c ao:accOwnersList){
                        if(ao.Account__c == opp.AccountID && ao.Show__c == opp.Event__r.Show__c && ao.SubShow__c == Null && opp.SubExpo__r.SubShow__c == Null){
                            Opportunity UpdateOpp = new Opportunity();
                            UpdateOpp.Id = opp.Id;
                            UpdateOpp.OwnerId = ao.AccountOwner__c;
                            updateOppwithAOList.add(UpdateOpp);
                            UpdatedOppIds.add(UpdateOpp.Id);
                        }
                        if(ao.Account__c == opp.AccountID && ao.Show__c == opp.Event__r.Show__c && ao.SubShow__c != Null && ao.SubShow__c == opp.SubExpo__r.SubShow__c){
                            Opportunity UpdateOpp1 = new Opportunity();
                            UpdateOpp1.Id = opp.Id;
                            UpdateOpp1.OwnerId = ao.AccountOwner__c;
                            updateOppwithAOList.add(UpdateOpp1);
                            UpdatedOppIds.add(UpdateOpp1.Id);
                        }
        
                    }
                }
                if(updateOppwithAOList.Size()>0){
                    update updateOppwithAOList;
                }
            }
        
            //
            
            List<Opportunity> oppList2 = new List<Opportunity>([Select Id,Should_Ignore_Assignment_Rule__c, Event__r.Show__c, Event__r.Show__r.Name, Event__r.Show__r.OwnerId, subexpo__r.subshow__r.rule_set__c, AccountID, AccountNameFirstChar__c, OwnerId,Show__c,SubExpo__r.SubShowName__c, BillingCountryandStateCode__c, Billing_Country_Code__c,Billing_State_Code__c,Rule_Set__c, 
                                                            SubExpo__r.Target_Booth_Revenue__c,SubExpo__r.Name, SubExpo__r.SubShow__c, SubExpo__r.SubShow__r.Name,SubExpo__r.Stage_Date__c,ShowObjectid__c,SubExpoObjectID__c,Pavilion__c
                                                            from Opportunity where Id IN :oppIds and Id Not IN: UpdatedOppIds
                                                            and Should_Ignore_Assignment_Rule__c = FALSE
                                                            and Rule_Set__c !='Disabled'
                                                            and Rule_Set__c != NULL
                                                            and Rule_Set__c != ''
                                                            ]);  
    
            Set<String> TerritoryRulesSet = new Set<String>();
            for(opportunity op : oppList2) {
                TerritoryRulesSet.add(op.Rule_Set__c);
            }
            
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:TerritoryRulesSet = ' + TerritoryRulesSet);             
            
            List<Territory_Rule__c> TerritoryRules  = new List<Territory_Rule__c>([Select Name__c,Key1__c,Key2__c, OpportunityOwner__c,Rule_Set__c,Territory_Rule_Type__c, Territory_Rule_ID__c from Territory_Rule__c where Rule_Set__c IN: TerritoryRulesSet and IsActiveUser__c = TRUE order by Name__c ASC]);
            
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:found rules = ' + TerritoryRules);
            
            for(Opportunity oPP : oppList2) {
                
                if(oPPIDSet.contains(oPP.id))
                    continue;
                if(TerritoryRules.size() >0){
                    for(Territory_Rule__c tr: TerritoryRules){
                        if(oPPIDSet.contains(oPP.id))
                            continue;
                            //Account Name
                            if(oPP.Rule_Set__c == tr.Rule_Set__c){   
                                if(tr.Territory_Rule_Type__c == RT_AccountName ){
                                    if(tr.Key1__c.contains(oPP.AccountNameFirstChar__c) ){                             
                                        oPP.OwnerId=tr.OpportunityOwner__c;
                                        lstOppsToBeUpdated.add(oPP);
                                        oPPIDSet.add(oPP.id);
                                        System.debug('@@@@@@@@@@@@@@@@@@@@@' +oPP);
                                        continue;
                                    }
                                }     
                            }
                            
                            //Billing State
                            if(tr.Territory_Rule_Type__c == RT_BillingState){
                                if(String.IsNotBlank(tr.Key1__c) && tr.Key1__c.contains(oPP.Billing_Country_Code__c)){
                                    if(tr.Key2__c=='*') {
                                    // Territory Rules is for the entire country
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@11111' +oPP);
                                    continue;
                                    
                                    } else if ( tr.Key2__c.contains(oPP.Billing_State_Code__c)) {
                                    //Country and State match territory rule
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@2222222' +oPP);
                                    continue;
                                    }
                                } 
                                system.debug('############'+oPP.Billing_Country_Code__c);
                                system.debug('44444444444444'+tr.Key2__c);
                                if(tr.Key1__c== International  && String.IsNotBlank(tr.Key2__c) && oPP.Billing_Country_Code__c != 'NULL' && !tr.Key2__c.contains(oPP.Billing_Country_Code__c) && oPP.Billing_Country_Code__c!= Country_US) {
                                    //International rules except US and whatever countries listed in Key2__c.
                                    //Some times show don't consider Canada as part of international countries                 
                                    oPP.OwnerId=tr.OpportunityOwner__c;
                                    lstOppsToBeUpdated.add(oPP);
                                    oPPIDSet.add(oPP.id);
                                    System.debug('@@@@@@@@@@@@@@@@@@@@@333333' +oPP);
                                    continue;                                            
                                }
                            }
                    
                            //Show
                            if(tr.Territory_Rule_Type__c == RT_Show && tr.Key1__c.contains(oPP.Event__r.Show__r.Name)){
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);
                                System.debug('@@@@@@@@@@@@@@@@@@@@@44444444444444' +oPP);
                                continue;                                            
                            }
                    
                            //Sub Show
                            if(tr.Territory_Rule_Type__c == RT_SubShow && oPP.SubExpo__r.SubShowName__c != null && tr.Key1__c.contains(oPP.SubExpo__r.SubShowName__c)){
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);
                                System.debug('@@@@@@@@@@@@@@@@@@@@@5555' +oPP);
                                continue;                                            
                            }
                            system.debug('@@@@@@@@@@@@@@@@@oPP.BillingCountryandStateCode__c'+oPP.BillingCountryandStateCode__c);
                            //Account Name and Billing State
                            if(tr.Territory_Rule_Type__c == RT_ANBS && tr.Key1__c.contains(oPP.AccountNameFirstChar__c) && !string.isBlank(oPP.BillingCountryandStateCode__c) && tr.Key2__c.contains(oPP.BillingCountryandStateCode__c)){ 
                                oPP.OwnerId=tr.OpportunityOwner__c;
                                lstOppsToBeUpdated.add(oPP);
                                oPPIDSet.add(oPP.id);

                                System.debug('@@@@@@@@@@@@@@@@@@@@@66666' +oPP);
                                continue;                                            
                            }                   
                    }
                }

                if(TerritoryRules.size() == 0){
                    oPP.OwnerId = oPP.Event__r.Show__r.OwnerId;
                    lstOppsToBeUpdated.add(oPP);
                    oPPIDSet.add(oPP.id); 
                }
            }
            //Update Opportunity with udpated owner

            
            update lstOppsToBeUpdated;
            System.debug('ee_defaultOPPOwner::defaultOpportunityOwner:lstOppsToBeUpdated = '+lstOppsToBeUpdated);
    }
        
        
    Public static void AccountOwnerUpsert(Set<Id> oppIds ){
            
        Set<Id> AccountIds = new Set<Id>();
        
        Set<Id> ShowIds = new Set<Id>();
        Set<Id> SubShowIds = new Set<Id>();
        Set<Id> showsWithoutSubshows = new Set<Id>();
        Set<Id> showsWithSubshows = new Set<Id>();

        Set<Id> processedShowIds = new Set<Id>();
        Set<Id> processedSubShowIds = new Set<Id>();

        List<AccountOwners__c> newAccountOwners = new List<AccountOwners__c>(); 
        List<AccountOwners__c> updateAccountOwners = new List<AccountOwners__c>();

        //List<Opportunity> OppList = [Select Id, OwnerId, Event__c, Event__r.Show__c, SubShow__c, SubExpo__c, SubExpo__r.SubShow__c, AccountId, ConvertedfromLead__c from Opportunity where Id IN: oppIds and ConvertedfromLead__c = True];
        Id dmUserId = [select id, Name from user where Name = 'Data Migration'].Id;
        List<Opportunity> OppList = [Select Id, OwnerId, Owner.Name, Event__c, Event__r.Show__c, Lead_Id__c, SubShow__c, SubExpo__c, SubExpo__r.SubShow__c, AccountId, StageName from Opportunity where Id IN: oppIds and OwnerID !=: dmUserId ];
        
        for(opportunity op: OppList){
            AccountIds.add(op.AccountId);

        }
        system.debug('******************** OppList'+OppList);
        List<AccountOwners__c> existingAccountOwners = [SELECT AccountOwner__c,Account__c,Id,Show__c,SubShow__c FROM AccountOwners__c where Account__c IN: AccountIds];
        
        for(AccountOwners__c tempEAC: existingAccountOwners){
            if(tempEAC.Show__c != null){
                ShowIds.add(tempEAC.Show__c);
            }
            system.debug('@@@@@@@@@@ShowIds'+ShowIds);

            if(tempEAC.SubShow__c != null){
                SubShowIds.add(tempEAC.SubShow__c);
            }
            system.debug('@@@@@@@@@@SubShowIds'+SubShowIds);

            if(tempEAC.Show__c != null && tempEAC.SubShow__c == null){
                showsWithoutSubshows.add(tempEAC.Show__c);
            }
            if(tempEAC.Show__c != null && tempEAC.SubShow__c != null){
                showsWithSubshows.add(tempEAC.Show__c);
            }
            
        }

        for(Opportunity tempOpp: OppList){
            if(existingAccountOwners.size() > 0){
                for(AccountOwners__c eac: existingAccountOwners){
                    system.debug('tempOpp.AccountId'+tempOpp.AccountId);
                    system.debug('eac.Account__c'+eac.Account__c);
                    system.debug('tempOpp.Event__r.Show__c'+tempOpp.Event__r.Show__c); 
                    system.debug('tempOpp.SubExpo__r.SubShow__c '+tempOpp.SubExpo__r.SubShow__c );
                    system.debug('ShowIds.contains(tempOpp.Event__r.Show__c)'+ShowIds.contains(tempOpp.Event__r.Show__c));
                    system.debug('showsWithoutSubshows.contains(tempOpp.Event__r.Show__c)'+showsWithoutSubshows.contains(tempOpp.Event__r.Show__c));
                    system.debug('processedShowIds.contains(tempOpp.Event__r.Show__c)'+processedShowIds.contains(tempOpp.Event__r.Show__c));
                    if(tempOpp.AccountId == eac.Account__c && tempOpp.SubExpo__r.SubShow__c== null && (!ShowIds.contains(tempOpp.Event__r.Show__c) || !showsWithoutSubshows.contains(tempOpp.Event__r.Show__c) ) && !processedShowIds.contains(tempOpp.Event__r.Show__c)){
                        AccountOwners__c accOwnr = new AccountOwners__c();
                        accOwnr.Account__c= tempOpp.AccountId;
                        accOwnr.AccountOwner__c= tempOpp.OwnerId;
                        accOwnr.Show__c = tempOpp.Event__r.Show__c;
                        accOwnr.SubShow__c = tempOpp.SubExpo__r.SubShow__c;
                        newAccountOwners.add(accOwnr);

                        processedShowIds.add(tempOpp.Event__r.Show__c);
                        
                        if(tempOpp.SubExpo__r.SubShow__c != null){
                            processedSubShowIds.add(tempOpp.SubExpo__r.SubShow__c);
                        }
                        continue;
                        system.debug('@@@@@@@@@@'+accOwnr);
                    }

                    if(tempOpp.AccountId == eac.Account__c && ShowIds.contains(tempOpp.Event__r.Show__c)  && tempOpp.SubExpo__r.SubShow__c != null && !SubShowIds.contains(tempOpp.SubExpo__r.SubShow__c) && !processedSubShowIds.contains(tempOpp.SubExpo__r.SubShow__c)){
                        AccountOwners__c accOwnr = new AccountOwners__c();
                        accOwnr.Account__c= tempOpp.AccountId;
                        accOwnr.AccountOwner__c= tempOpp.OwnerId;
                        accOwnr.Show__c = tempOpp.Event__r.Show__c;
                        accOwnr.SubShow__c = tempOpp.SubExpo__r.SubShow__c;
                        newAccountOwners.add(accOwnr);

                        processedShowIds.add(tempOpp.Event__r.Show__c);
                        
                        if(tempOpp.SubExpo__r.SubShow__c != null)
                        processedSubShowIds.add(tempOpp.SubExpo__r.SubShow__c);

                        continue;
                        system.debug('@@@@@@@@@@!!!!'+accOwnr);
                    }
                    
                    if(tempOpp.AccountId == eac.Account__c && ShowIds.contains(tempOpp.Event__r.Show__c) && !processedShowIds.contains(tempOpp.Event__r.Show__c) && tempOpp.Event__r.Show__c == eac.Show__c && tempOpp.SubExpo__r.SubShow__c == null && eac.SubShow__c == null && tempOpp.OwnerID != eac.AccountOwner__c){
                        AccountOwners__c accOwnr = new AccountOwners__c();
                        accOwnr.id =  eac.id;
                        accOwnr.AccountOwner__c= tempOpp.OwnerId;
                        updateAccountOwners.add(accOwnr);

                        processedShowIds.add(tempOpp.Event__r.Show__c);
                        
                        if(tempOpp.SubExpo__r.SubShow__c != null)
                        processedSubShowIds.add(tempOpp.SubExpo__r.SubShow__c);

                        system.debug('@@@@@@@@@@tempOpp1'+tempOpp);
                        continue;
                    }

                    if(tempOpp.AccountId == eac.Account__c && ShowIds.contains(tempOpp.Event__r.Show__c) && SubShowIds.contains(tempOpp.SubExpo__r.SubShow__c) && !processedSubShowIds.contains(tempOpp.SubExpo__r.SubShow__c) && tempOpp.Event__r.Show__c == eac.Show__c && tempOpp.SubExpo__r.SubShow__c != null && tempOpp.SubExpo__r.SubShow__c == eac.SubShow__c && tempOpp.OwnerID != eac.AccountOwner__c){
                        AccountOwners__c accOwnr = new AccountOwners__c();
                        accOwnr.id =  eac.id;
                        accOwnr.AccountOwner__c = tempOpp.OwnerId;
                        updateAccountOwners.add(accOwnr);

                        processedShowIds.add(tempOpp.Event__r.Show__c);
                        
                        if(tempOpp.SubExpo__r.SubShow__c != null)
                        processedSubShowIds.add(tempOpp.SubExpo__r.SubShow__c);

                        system.debug('@@@@@@@@@@tempOpp2'+tempOpp);
                        continue;
                    }
                }
            }
            if(existingAccountOwners.size() == 0){
                AccountOwners__c accOwnr = new AccountOwners__c();
                accOwnr.Account__c = tempOpp.AccountId;
                accOwnr.AccountOwner__c= tempOpp.OwnerId;
                accOwnr.Show__c = tempOpp.Event__r.Show__c;
                accOwnr.SubShow__c = tempOpp.SubExpo__r.SubShow__c;
                newAccountOwners.add(accOwnr);
                system.debug('@@@@@@@@@@###'+accOwnr);
            }
        }
        
        if(newAccountOwners.size() > 0){ 
            insert newAccountOwners;
            system.debug('@@@@@@@@@@newAccountOwners'+newAccountOwners);
        }
        if(updateAccountOwners.size() > 0){
            update updateAccountOwners;
            system.debug('@@@@@@@@@@newAccountOwners'+updateAccountOwners);
        }
    }  */       
}