objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>if(begins(Subject,"P"), 
MID( 
Subject, 
FIND("|",Subject ) + 1, 
FIND("|",RIGHT(Subject, LEN(Subject) - FIND ("|",Subject ) -1 ))) 
,"")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Activity_Result_Mapping__c.object
<CustomObject>
    <description>Used by trigger to determine which Campaign Member Status to update based on the Activity Result set by Attend Reps</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Activity Result Mapping</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Result Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booth</fullName>
                </value>
                <value>
                    <fullName>Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>VIP Registration</fullName>
                </value>
                <value>
                    <fullName>Conference Registration</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Hosted Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Technique__c</fullName>
        <label>Technique</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Inbound Inquiry</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Attendee</fullName>
        <active>true</active>
        <label>Attendee</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <formula>Contact.ContactGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactGUID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <formula>CASESAFEID(Campaign.Event__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/CampaignMemberStatusTemplate__c.object
<CustomObject>
    <description>Used to set the list of available Campaign Member Status for Campaign by Product</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <label>Campaign Member Status Template</label>
    <nameField>
        <label>Campaign Member Status Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member Status Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <inlineHelpText>Edge reference ID</inlineHelpText>
        <label>ContactGUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Booth_Last_Date__c</fullName>
        <label>Booth Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Code__c</fullName>
        <label>Event Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Year__c</fullName>
        <label>Event Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gift, Home, &amp; Gen Mchds</fullName>
                </value>
                <value>
                    <fullName>Sports &amp; Apparel</fullName>
                </value>
                <value>
                    <fullName>Licensing</fullName>
                </value>
                <value>
                    <fullName>Jewelry, Luxury &amp; Antiques</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design/Healthcare</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_Booth_Last_Date__c</fullName>
        <label>Non-Booth Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Start_Date__c</fullName>
        <description>Start Date</description>
        <label>Opportunity Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Event_Code__c</fullName>
        <description>Event Code from Registration System (EventXL)</description>
        <externalId>true</externalId>
        <label>Registration Event Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <formula>Show__r.Show_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <infoMessage>Selected event must belong to the specified show.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <defaultValue>"Booth"</defaultValue>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Booth</fullName>
        <default>true</default>
        <label>Booth</label>
    </customValue>
    <customValue>
        <fullName>Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>List rental</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Print</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>VIP Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Conference Registration</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

classes/EE_UpdateStatusonCampaignMemberTest.cls
@isTest
public class EE_UpdateStatusonCampaignMemberTest{
    static testmethod void EE_UpdateStatusonCampaignMemberTest() {

        date myDate = date.today();
        Date newDate = mydate.addDays(2);
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;

        // Create contacts
        Contact ct1 = new Contact();
        ct1.FirstName = 'Emerald';
        ct1.LastName = 'Test';
        ct1.Email = 'EmeraldTest@ee.com';
        ct1.AccountId = account.Id;
        ct1.ContactGUID__c = 'TEST-TEST-TEST20';
        insert ct1;

        //Create Show 
		Show__c show = new Show__c();
		show.Name='Test Show';
		show.Brand__c='TBrand';
		show.Market__c='TMarket';
		show.Rule_Set__c='ASD_SB';
		show.Segment__c='TSegment';
		show.Show_Code__c='TShowCode';      
		show.Show_Group__c='ShowGroup';
		show.ShowID__c=12345;
        insert show;
    
       //Create Event
		Event__c event = new Event__c();
		event.Name='Test Event';
		event.Show__c=show.id;
		event.Event_Year__c='2019';
		event.Event_Code__c='2019-01';
		event.Stage_Date__c=myDate;
		event.Opportunity_Start_Date__c=myDate;
		event.Booth_Last_Date__c=newDate;
        event.Non_Booth_Last_Date__c=newDate;
        event.Registration_Event_Code__c ='ASD20';
        insert event;
        
        
        Id RecordTypeIdCampaign = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Attendee').getRecordTypeId();
        
        //Create Campaign
		Campaign camp = new Campaign();
		camp.Name = 'Camp1';
		camp.Short_Description__c='Test Camp1';
        camp.Event__c=event.id;
        camp.Product__c='VIP Registration';
        camp.RecordTypeId = RecordTypeIdCampaign;
        camp.Status='In Progress';
        camp.Technique__c= 'Call';
        camp.Target_Start_Date__c=myDate;
        camp.Target_End_Date__c =myDate;
        camp.Target_num_of_records__c = 20;
        insert camp;		

        //Campaign Member
        CampaignMember cm = new CampaignMember();
        cm.CampaignId= camp.Id;
        cm.ContactId = ct1.Id;
        cm.Owner__c = UserInfo.getUserId();
        cm.Status='Follow Up Required ';
        insert cm;

        //Create CampaignMemberStatusTemplate
        CampaignMemberStatusTemplate__c cmst = new CampaignMemberStatusTemplate__c();
        cmst.ActivityResult__c = 'Replied to Email';
        cmst.Label__c = 'Test1';
        cmst.Name = 'Test1';
        cmst.Product__c = 'VIP Registration';
        cmst.SortOrder__c = 4;
        insert cmst;

        //Create CampaignMemberStatusTemplate
        CampaignMemberStatusTemplate__c cmst2 = new CampaignMemberStatusTemplate__c();
        cmst2.ActivityResult__c = 'Replied to Email';
        cmst2.Label__c = 'Test2';
        cmst2.Name = 'Test2';
        cmst2.Product__c = 'VIP Registration';
        cmst2.SortOrder__c = 5;
        insert cmst2;

        //Create CampaignMemberStatusTemplate
        CampaignMemberStatusTemplate__c cmst3 = new CampaignMemberStatusTemplate__c();
        cmst3.ActivityResult__c = 'Replied to Email';
        cmst3.Label__c = 'Test3';
        cmst3.Name = 'Test3';
        cmst3.Product__c = 'VIP Registration';
        cmst3.SortOrder__c = 6;
        insert cmst3;

        //Create CampaignMemberStatusTemplate
        CampaignMemberStatusTemplate__c cmst1 = new CampaignMemberStatusTemplate__c();
        cmst1.ActivityResult__c = 'No answer';
        cmst1.Label__c = 'No Answer';
        cmst1.Name = 'No Answer';
        cmst1.Product__c = 'VIP Registration';
        cmst1.SortOrder__c = 3;
        insert cmst1;

        //Create Activity Result Mapping
        Activity_Result_Mapping__c arm = new Activity_Result_Mapping__c();
        arm.Activity_Result__c ='Replied to Email';
        arm.Campaign_Member_Status_Template__c	= cmst.id;
        arm.Product__c ='VIP Registration';
        arm.Exclude_Statuses__c = 'Registered, Commitment Made, Follow Up Required, Not Interested';
        insert arm;

        //Create Activity Result Mapping
        Activity_Result_Mapping__c arm2 = new Activity_Result_Mapping__c();
        arm2.Activity_Result__c ='Replied to Email';
        arm2.Campaign_Member_Status_Template__c	= cmst2.id;
        arm2.Product__c ='VIP Registration';
        arm2.Exclude_Statuses__c = 'Registered, Commitment Made, Follow Up Required, Not Interested';
        insert arm2;

        //Create Activity Result Mapping
        Activity_Result_Mapping__c arm3 = new Activity_Result_Mapping__c();
        arm3.Activity_Result__c ='Replied to Email';
        arm3.Campaign_Member_Status_Template__c	= cmst3.id;
        arm3.Product__c ='VIP Registration';
        arm3.Exclude_Statuses__c = 'Registered, Commitment Made, Follow Up Required, Not Interested';
        insert arm3;

        //Create Activity Result Mapping
        Activity_Result_Mapping__c arm1 = new Activity_Result_Mapping__c();
        arm1.Activity_Result__c ='No answer';
        arm1.Campaign_Member_Status_Template__c	= cmst1.id;
        arm1.Product__c ='VIP Registration';
        arm1.Exclude_Statuses__c = 'Registered, Commitment Made, Follow Up Required, Not Interested';
        insert arm1;

        // Create Task
        Task task = new Task();
        task.Event__c = event.id;
        task.Campaign__c = camp.id;
        task.WhoId = ct1.id;
        task.Activity_Result__c ='Replied to Email';
        task.Status ='Not Started';
        task.Priority ='Normal';
        task.OwnerId = UserInfo.getUserId();

        // Create Task
        Task task1 = new Task();
        task1.Event__c = event.id;
        task1.Campaign__c = camp.id;
        task1.WhoId = ct1.id;
        task1.Activity_Result__c ='Replied to Email';
        task1.Status ='Not Started';
        task1.Priority ='Normal';
        task1.OwnerId = UserInfo.getUserId();

        // Create Task
        Task task3 = new Task();
        task3.Event__c = event.id;
        task3.Campaign__c = camp.id;
        task3.WhoId = ct1.id;
        task3.Activity_Result__c ='Replied to Email';
        task3.Status ='Not Started';
        task3.Priority ='Normal';
        task3.OwnerId = UserInfo.getUserId();

        // Create Task
        Task task2 = new Task();
        task2.Event__c = event.id;
        task2.Campaign__c = camp.id;
        task2.WhoId = ct1.id;
        task2.Activity_Result__c ='No answer';
        task2.Status ='Not Started';
        task2.Priority ='Normal';
        task2.OwnerId = UserInfo.getUserId();

        test.startTest();
        insert task;
        insert task1;
        insert task3;
        insert task2;
        test.stopTest(); 
    }
}