objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Activity_Result__c</fullName>
        <inlineHelpText>Activity Result is required when Campaign is populated</inlineHelpText>
        <label>Activity Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Contact made</fullName>
                </value>
                <value>
                    <fullName>Invalid Number</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Replied to Email</fullName>
                </value>
                <value>
                    <fullName>Returned Voicemail</fullName>
                </value>
                <value>
                    <fullName>Voicemail box full</fullName>
                </value>
                <value>
                    <fullName>Voicemail left</fullName>
                </value>
                <value>
                    <fullName>Lead Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Activity_Result_Mapping__c.object
<CustomObject>
    <description>Used by trigger to determine which Campaign Member Status to update based on the Activity Result set by Attend Reps</description>
    <fields>
        <fullName>Activity_Result__c</fullName>
        <label>Activity Result</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Status_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign Member Status Template</label>
        <referenceTo>CampaignMemberStatusTemplate__c</referenceTo>
        <relationshipLabel>Activity Result Mappings</relationshipLabel>
        <relationshipName>Activity_Result_Mappings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_Statuses__c</fullName>
        <description>List of campaign member statuses we should not override based on activity results</description>
        <label>Exclude Statuses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <formula>Campaign_Member_Status_Template__r.SortOrder__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SortOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Activity Result Mapping</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Result Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booth</fullName>
                </value>
                <value>
                    <fullName>Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>VIP Registration</fullName>
                </value>
                <value>
                    <fullName>Conference Registration</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Hosted Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/CampaignMemberStatusTemplate__c.object
<CustomObject>
    <description>Used to set the list of available Campaign Member Status for Campaign by Product</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Campaign Member Status Template</label>
    <nameField>
        <label>Campaign Member Status Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member Status Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Booth</fullName>
        <default>true</default>
        <label>Booth</label>
    </customValue>
    <customValue>
        <fullName>Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>List rental</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Print</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>VIP Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Conference Registration</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

globalValueSets/Relationship_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Attendee</fullName>
    </customValue>
    <customValue>
        <fullName>Exhibitor</fullName>
    </customValue>
    <masterLabel>Relationship Type</masterLabel>
</GlobalValueSet>

classes/EE_UpdateStatusonCampaignMember.cls
/*
Dev: Spoorthy Teegala
Date:05/15/2020
Description:Trigger handler to update status on CampaignMember based on task activity result field.
*/
public class EE_UpdateStatusonCampaignMember{

    public static void updateStatusOnCampaignMember(Set<ID> taskIds){
        
        List<CampaignMember> updateCampMemberList = new List<CampaignMember>();
        List<Task> taskList = new List<Task>();
        Set<Id> whoIdSet = new Set<Id>();
        Set<Id> whatIdSet = new Set<Id>();
        Set<Id> contIdSet = new Set<Id>();
        Set<String> productSet = new Set<String>();
        Set<Id> campIdSet = new Set<Id>();
        Set<Id> processedCampMemIdSet = new Set<Id>();
        Set<String> statusValueSet = new Set<String>();
        Set<String> ActResValueSet = new Set<String>();
        List<String> excludeValues = new List<String>();
        List<String> excludeStatusList = new List<String>();

        taskList = [Select Id,Activity_Result__c,Status,whatId,WhoId from Task where Id IN:taskIds AND Activity_Result__c != Null];
        system.debug('taskList'+taskList);
        for(Task task: taskList){
            whoIdSet.add(task.WhoId);
            whatIdSet.add(task.WhatId);
        }

        List<Contact> conList = [Select Id, Relationship_Type__c from Contact where Id IN: whoIdSet];
        system.debug('conList'+conList);
        for(Contact cont: conList){
            contIdSet.add(cont.Id);
        }
           
        List<Campaign> campList = [Select Id, Product__c from Campaign where Id IN:whatIdSet]; 
        system.debug('campList'+campList);
        for(Campaign c: campList){
            productSet.add(c.Product__c);
            campIdSet.add(c.Id);
        }

        Map<String, Activity_Result_Mapping__c> activityResultMappingMap = new Map<String, Activity_Result_Mapping__c>();
        List<Activity_Result_Mapping__c> activityResultMapList = [Select Id, Name, Product__c, Exclude_Statuses__c, Activity_Result__c, SortOrder__c, Campaign_Member_Status_Template__r.Name from Activity_Result_Mapping__c where Product__c IN: productSet AND Activity_Result__c != Null Order By SortOrder__c ASC];
        system.debug('activityResultMapList'+activityResultMapList);
        
		if(activityResultMapList.size() > 0){
            if(String.IsNotBlank(activityResultMapList[0].Exclude_Statuses__c)){
                excludeValues = activityResultMapList[0].Exclude_Statuses__c.split(',');
            }

            if(excludeValues.size() >0){
                for(string exv: excludeValues){
                    excludeStatusList.add(exv.trim());
                }

            }

            system.debug('excludeStatusList'+excludeStatusList);
		}
		
		for(Activity_Result_Mapping__c armmap: activityResultMapList){
			
            activityResultMappingMap.put(String.ValueOf(armmap.SortOrder__c)+armmap.Activity_Result__c,armmap);
			
            if(armmap.SortOrder__c == 4 || armmap.SortOrder__c == 5 || armmap.SortOrder__c == 6){
                statusValueSet.add(armmap.Campaign_Member_Status_Template__r.Name);
                ActResValueSet.add(armmap.Activity_Result__c);
                
            }
        }
        system.debug('statusValueSet'+statusValueSet);

        Id currentUserId = UserInfo.getUserId();
        
        Set<String> statusSet = new Set<String>();
        List<CampaignMember> cMList = [Select Id, CampaignId, Status, ContactId, Owner__c from CampaignMember where CampaignId IN: campIdSet AND ContactId IN: contIdSet AND Owner__c =: currentUserId AND Status NOT IN: excludeStatusList];
        system.debug('cMList'+cMList);
        
        for(Task t: taskList){
            for(Activity_Result_Mapping__c arm: activityResultMapList){
                for(CampaignMember cm: cMList){
					
                    String cmstName = activityResultMappingMap.get(String.ValueOf(arm.SortOrder__c)+arm.Activity_Result__c).Campaign_Member_Status_Template__r.Name;
                    
                    if(!processedCampMemIdSet.contains(cm.Id) && arm.Activity_Result__c.contains(t.Activity_Result__c) && !statusValueSet.contains(cmstName)){
                        CampaignMember campMem = new CampaignMember();
                        campMem.Id = cm.id;
                        campMem.Status = arm.Campaign_Member_Status_Template__r.Name;
                        updateCampMemberList.add(campMem);
                        processedCampMemIdSet.add(cm.id);
                    }
                    if(ActResValueSet.contains(t.Activity_Result__c)){
                        if(!processedCampMemIdSet.contains(cm.Id) && arm.Activity_Result__c.contains(t.Activity_Result__c) && !(cmstName.right(1)).equals((cm.status).right(1)) && ((cm.status).right(1)).isNumeric() == false ){
                            CampaignMember campMem = new CampaignMember();
                            campMem.Id = cm.id;
                            campMem.Status = activityResultMappingMap.get(String.ValueOf(arm.SortOrder__c)+arm.Activity_Result__c).Campaign_Member_Status_Template__r.Name;
                            updateCampMemberList.add(campMem);
                            processedCampMemIdSet.add(cm.id);
                            system.debug('Entered 4');
                        }

                        if(!processedCampMemIdSet.contains(cm.Id) && arm.Activity_Result__c.contains(t.Activity_Result__c) && statusValueSet.contains(cmstName) &&  (cmstName.right(1)).equals((cm.status).right(1)) && arm.SortOrder__c == 4){
                            CampaignMember campMem = new CampaignMember();
                            campMem.Id = cm.id;
                            campMem.Status = activityResultMappingMap.get(String.ValueOf(Integer.ValueOf(arm.SortOrder__c+1))+arm.Activity_Result__c).Campaign_Member_Status_Template__r.Name;
                            updateCampMemberList.add(campMem);
                            processedCampMemIdSet.add(cm.id);
                            system.debug('Entered 5');
                        }
                        if(!processedCampMemIdSet.contains(cm.Id) && arm.Activity_Result__c.contains(t.Activity_Result__c) && statusValueSet.contains(cmstName) && (cmstName.right(1)).equals((cm.status).right(1))  && arm.SortOrder__c == 5){                        
                            CampaignMember campMem = new CampaignMember();
                            campMem.Id = cm.id;
                            campMem.Status = activityResultMappingMap.get(String.ValueOf(Integer.ValueOf(arm.SortOrder__c+1))+arm.Activity_Result__c).Campaign_Member_Status_Template__r.Name;
                            updateCampMemberList.add(campMem);
                            processedCampMemIdSet.add(cm.id);
                            system.debug('Entered 6');
                        }
                    }
					
                }
            }
        }  
        
        if(updateCampMemberList.size()>0){
            update updateCampMemberList;
            System.debug('updateCampMemberList'+updateCampMemberList);
            
        }
    }

}