objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booth</fullName>
                </value>
                <value>
                    <fullName>Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>VIP Registration</fullName>
                </value>
                <value>
                    <fullName>Conference Registration</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Hosted Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMemberStatusTemplate__c.object
<CustomObject>
    <description>Used to set the list of available Campaign Member Status for Campaign by Product</description>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Campaign Member Status Template</label>
    <nameField>
        <label>Campaign Member Status Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member Status Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Booth</fullName>
        <default>true</default>
        <label>Booth</label>
    </customValue>
    <customValue>
        <fullName>Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>List rental</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Print</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>VIP Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Conference Registration</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

classes/EE_AddCampaignMemberStatusTgrHandler.cls
/*
Dev: Spoorthy Teegala
Date: 05/14/2020
Description: Trigger handler to add CampaignMemberStatus values based on product on campaign when a campaign record is inserted.
*/
public class EE_AddCampaignMemberStatusTgrHandler {
    
    public static void addCampaignMemberStatusonCampaign(List<Campaign> campIds){
        
        List<CampaignMemberStatus> addCampaignMemberStatusList = new List<CampaignMemberStatus>();
        List<Campaign> campaignList =new List<Campaign>();
        List<CampaignMemberStatusTemplate__c> campaignMemberStatusTemplateList = new List<CampaignMemberStatusTemplate__c>();
        

        Set<String> productSet = new Set<String>();
        campaignList = [Select Id, Product__c from Campaign where Id IN: campIds];
        for(Campaign C: campaignList){
            productSet.add(C.Product__c);
        }

        campaignMemberStatusTemplateList = [Select Id, Product__c, HasResponded__c, IsDefault__c, Label__c, SortOrder__c from CampaignMemberStatusTemplate__c where Product__c IN: productSet];
        system.debug('CampaignMemberStatusTemplateList' +campaignMemberStatusTemplateList);
        
        for(Campaign camp: campaignList){
            for(CampaignMemberStatusTemplate__c cst: campaignMemberStatusTemplateList){
                if(camp.Product__c != Null && cst.Product__c != Null && camp.Product__c == cst.Product__c){
                    CampaignMemberStatus cms = new CampaignMemberStatus();
                    cms.CampaignId = camp.Id;
                    cms.Label = (cst.Label__c).trim();
                    cms.HasResponded = cst.HasResponded__c;
                    cms.SortOrder = Integer.valueOf(cst.SortOrder__c);
                    cms.IsDefault = cst.IsDefault__c;
                    addCampaignMemberStatusList.add(cms);
                    system.debug('CampaignMemberStatus' +cms);
                }
            }

        }
        system.debug('AddCampaignMemberStatusList' +addCampaignMemberStatusList);
        if(addCampaignMemberStatusList.size()>0){
            insert addCampaignMemberStatusList;
        }
        
        if(addCampaignMemberStatusList.size()>0){
            List<CampaignMemberStatus> cMSListToDelete = [Select id from CampaignMemberStatus where CampaignId IN: campIds and (SortOrder = 1 or SortOrder = 2) ];
            system.debug('cMSListToDelete::'+cMSListToDelete);

            if(cMSListToDelete.size() > 0){
                delete cMSListToDelete;
            }
        }

    }

}