objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Attendee</fullName>
        <active>true</active>
        <label>Attendee</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <inlineHelpText>Edge reference ID</inlineHelpText>
        <label>ContactGUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EE_Integration_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EE_Integration_Queues</relationshipLabel>
        <relationshipName>EE_Integration_Queues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EE_Integration_Queue</label>
    <nameField>
        <displayFormat>EEMCQ-{0}</displayFormat>
        <label>EE_Integration_Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EE_Integration_Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <label>Event Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Year__c</fullName>
        <label>Event Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gift, Home, &amp; Gen Mchds</fullName>
                </value>
                <value>
                    <fullName>Sports &amp; Apparel</fullName>
                </value>
                <value>
                    <fullName>Licensing</fullName>
                </value>
                <value>
                    <fullName>Jewelry, Luxury &amp; Antiques</fullName>
                </value>
                <value>
                    <fullName>Photo</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Design/Healthcare</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Start_Date__c</fullName>
        <description>Start Date</description>
        <label>Opportunity Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <formula>Show__r.Show_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Event__r.Show__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Year__c</fullName>
        <formula>Text(Event__r.Event_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Event__r.Show__r.Market__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <formula>BLANKVALUE(SubExpo__r.SubShow__r.Rule_Set__c,Event__r.Show__r.Rule_Set__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rule Set</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>Event__r.Show__r.Segment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityContactRole.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <formula>Contact.ContactGUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactGUID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <formula>CASESAFEID( Opportunity.Event__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event__c.Show__c</field>
                <operation>equals</operation>
                <valueField>$Source.Show__c</valueField>
            </filterItems>
            <infoMessage>Selected event must belong to the specified show.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubExpo__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <label>SubExpo</label>
    <nameField>
        <label>SubExpo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubExpos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubShow__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>SubShows</relationshipLabel>
        <relationshipName>SubShows</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SubShow</label>
    <nameField>
        <label>SubShow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubShows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_Job_MCInboundOppIntegrationTest.cls
@isTest
public class EE_Job_MCInboundOppIntegrationTest {
    @testSetup 
    static void setup() {
        date myDate = date.today();
        Date newDate = mydate.addDays(2);
        
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;
        
        // Create contacts
        Contact ct1 = new Contact();
        ct1.FirstName = 'Emerald';
        ct1.LastName = 'Test';
        ct1.Email = 'EmeraldTest@ee.com';
        ct1.AccountId = account.Id;
        ct1.ContactGUID__c = 'TEST-TEST-TEST20';
        insert ct1;
        
        //Create Show 
        Show__c show = new Show__c();
        show.Name='Test Show';
        show.Brand__c='TBrand';
        show.Market__c='TMarket';
        show.Rule_Set__c='ASD_SB';
        show.Segment__c='TSegment';
        show.Show_Code__c='TShowCode';      
        show.Show_Group__c='ShowGroup';
        show.ShowID__c=12345;
        insert show;
       
        //Create Event
        Event__c event = new Event__c();
        event.Name='Test Event';
        event.Show__c=show.id;
        event.Event_Year__c='2020';
        event.Event_Code__c='2020-01';
        event.Stage_Date__c=myDate;
        event.Opportunity_Start_Date__c=myDate;
        event.Booth_Last_Date__c=newDate;
        event.Non_Booth_Last_Date__c=newDate;
        insert event;
      
        Id RecordTypeIdCampaign = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Attendee').getRecordTypeId();
        
        //Create Campaign
		Campaign camp = new Campaign();
		camp.Name = 'Camp1';
		camp.Short_Description__c='Test Camp1';
        camp.Event__c=event.id;
        camp.Product__c='VIP Registration';
        camp.RecordTypeId = RecordTypeIdCampaign;
        camp.Status='In Progress';
        camp.Technique__c= 'Call';
        camp.Target_Start_Date__c=myDate;
        camp.Target_End_Date__c =myDate;
        camp.Target_num_of_records__c = 20;	
        insert camp;	

        //Create Sub Show
        SubShow__c subshow = new SubShow__c();
        subshow.Name = 'subshow';
        subshow.Show__c=show.id; 
        insert subshow;
       
        // Create Sub Expo
        SubExpo__c subexpo = new SubExpo__c();
        subexpo.Name = 'Test SubExpo';
        subexpo.SubShow__c=subShow.id;
        subexpo.Event__c=event.id;
        insert subexpo;

        //Create Integration Queue
        EE_Integration_Queue__c IQ1 = new EE_Integration_Queue__c();
        IQ1.Campaign__c = camp.Id;
        IQ1.Contact__c = ct1.Id;
        IQ1.Event__c = event.Id;
        IQ1.Object_Name__c = 'Opportunity';
        IQ1.Product__c ='VIP Registration';
        IQ1.SubExpo__c = subexpo.Id;
        insert IQ1;

        //Exsisting Records
        //Create Event
        Event__c event1 = new Event__c();
        event1.Name='Test Event2';
        event1.Show__c=show.id;
        event1.Event_Year__c='2020';
        event1.Event_Code__c='1234-01';
        event1.Stage_Date__c=myDate;
        event1.Opportunity_Start_Date__c=myDate;
        event1.Booth_Last_Date__c=newDate;
        event1.Non_Booth_Last_Date__c=newDate;
        insert event1;

        // Create Sub Expo
        SubExpo__c subexpo1 = new SubExpo__c();
        subexpo1.Name = 'Surf';
        subexpo1.SubShow__c=subshow.id;
        subexpo1.Event__c=event1.id;
        insert subexpo1;

        //Create Campaign
		Campaign camp1 = new Campaign();
		camp1.Name = 'Camp1';
		camp1.Short_Description__c = 'Test Camp1';
        camp1.Event__c = event1.id;
        camp1.Product__c ='VIP Registration';
        camp1.RecordTypeId = RecordTypeIdCampaign;
        camp1.Status ='In Progress';
        camp1.Technique__c = 'Call';
        camp.Target_Start_Date__c = myDate;
        camp1.Target_End_Date__c = myDate;
        camp1.Target_num_of_records__c = 20;	
        insert camp1;
        
        // Create Opportunity without subexpo
		Opportunity opp = new Opportunity();
		opp.name = 'Opportunity Test';
		opp.AccountId = account.id;
		opp.CloseDate =  Date.today()+2;
		opp.StageName = 'No Contact Attempted';
		opp.Event__c = event1.id;
        opp.CampaignId = camp1.id;
        opp.Product__c = 'VIP Registration';
        insert opp;

        // Create Opportunity with subexpo
		Opportunity opp1 = new Opportunity();
		opp1.name = 'Opportunity Test';
		opp1.AccountId=account.id;
		opp1.CloseDate =  Date.today()+2;
		opp1.StageName = 'No Contact Attempted';
		opp1.Event__c = event1.id;
        opp1.CampaignId = camp1.id;
        opp1.SubExpo__c = subexpo1.id;
        opp1.Product__c = 'VIP Registration';
        insert opp1;

        // Create contacts
        Contact ct = new Contact();
        ct.FirstName = 'Emerald1';
        ct.LastName = 'Test1';
        ct.Email = 'EmeraldTest1@ee.com';
        ct.AccountId = account.Id;
        ct.ContactGUID__c = 'TEST-TEST-TEST20';
        insert ct;

        // Create contacts
        Contact ct2 = new Contact();
        ct2.FirstName = 'Emerald1';
        ct2.LastName = 'Test1';
        ct2.Email = 'EmeraldTest1@ee.com';
        ct2.AccountId = account.Id;
        ct2.ContactGUID__c = 'TEST-TEST-TEST20';
        insert ct2;

        // Create Opportunity without subexpo and OCR
		Opportunity opp2 = new Opportunity();
		opp2.name = 'Opportunity Test';
		opp2.AccountId = account.id;
		opp2.CloseDate =  Date.today()+2;
		opp2.StageName = 'No Contact Attempted';
		opp2.Event__c = event1.id;
        opp2.CampaignId = camp1.id;
        opp2.Product__c = 'VIP Registration';
        insert opp2;

        //create Ocr
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.OpportunityId=opp2.id;
        ocr.ContactId=ct.Id; 
        ocr.Role='Attendee Contact';
        insert ocr;

        // Create Opportunity with subexpo
		Opportunity opp3 = new Opportunity();
		opp3.name = 'Opportunity Test';
		opp3.AccountId=account.id;
		opp3.CloseDate =  Date.today()+2;
		opp3.StageName = 'No Contact Attempted';
		opp3.Event__c = event1.id;
        opp3.CampaignId = camp1.id;
        opp3.SubExpo__c = subexpo1.id;
        opp3.Product__c = 'VIP Registration';
        insert opp3;

        //create Ocr
        OpportunityContactRole ocr1 = new OpportunityContactRole();
        ocr1.OpportunityId=opp2.id;
        ocr1.ContactId=ct.Id; 
        ocr1.Role='Attendee Contact';
        ocr1.IsPrimary =True;
        insert ocr1;        
      
		//Create Integration Queue
        EE_Integration_Queue__c IQ2 = new EE_Integration_Queue__c();
        IQ2.Campaign__c = camp1.Id;
        IQ2.Contact__c = ct1.Id;
        IQ2.Event__c = event1.Id;
        IQ2.Object_Name__c = 'Opportunity';
        IQ2.Product__c ='VIP Registration';
        IQ2.SubExpo__c = subexpo1.Id;
        insert IQ2;
        
        //Create Integration Queue
        EE_Integration_Queue__c IQ3 = new EE_Integration_Queue__c();
        IQ3.Campaign__c = camp1.Id;
        IQ3.Contact__c = ct1.Id;
        IQ3.Event__c = event1.Id;
        IQ3.Object_Name__c = 'Opportunity';
        IQ3.Product__c ='VIP Registration';
        insert IQ3;
        
        //Create Integration Queue
        EE_Integration_Queue__c IQ4 = new EE_Integration_Queue__c();
        IQ4.Campaign__c = camp1.Id;
        IQ4.Contact__c = ct.Id;
        IQ4.Event__c = event1.Id;
        IQ4.Object_Name__c = 'Opportunity';
        IQ4.Product__c ='VIP Registration';
        insert IQ4;

        //Create Integration Queue
        EE_Integration_Queue__c IQ5 = new EE_Integration_Queue__c();
        IQ5.Campaign__c = camp1.Id;
        IQ5.Contact__c = ct.Id;
        IQ5.Event__c = event1.Id;
        IQ5.Object_Name__c = 'Opportunity';
        IQ5.Product__c ='VIP Registration';
        IQ5.SubExpo__c = subexpo1.Id;
        insert IQ5;

        //Create Integration Queue
        EE_Integration_Queue__c IQ6 = new EE_Integration_Queue__c();
        IQ6.Campaign__c = camp1.Id;
        IQ6.Contact__c = ct2.Id;
        IQ6.Event__c = event1.Id;
        IQ6.Object_Name__c = 'Opportunity';
        IQ6.Product__c ='VIP Registration';
        insert IQ6;

        //Create Integration Queue
        EE_Integration_Queue__c IQ7 = new EE_Integration_Queue__c();
        IQ7.Campaign__c = camp1.Id;
        IQ7.Contact__c = ct2.Id;
        IQ7.Event__c = event1.Id;
        IQ7.Object_Name__c = 'Opportunity';
        IQ7.Product__c ='VIP Registration';
        IQ7.SubExpo__c = subexpo1.Id;
        insert IQ7;
   
    }
    static testmethod void test(){        
        Test.startTest();
        
        EE_Job_MCInboundOpportunityIntegration mcInboundOppIntegrationtest = new EE_Job_MCInboundOpportunityIntegration();
        Database.executeBatch(mcInboundOppIntegrationtest);
        mcInboundOppIntegrationtest.alertEmeraldSFDCSupportTeam('Opportunity','Insert', 'Test Message');
        
        Test.stopTest();
    }
}