objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubExpo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubExpo__c.Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <label>Event Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_ID__c</fullName>
        <label>Event ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Year__c</fullName>
        <label>Event Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NextYear_Event_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Year Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Next Year Event</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <formula>Show__r.Show_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Upcoming_Event_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Up Coming Event (Event)</relationshipLabel>
        <relationshipName>Upcoming_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>EE_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Campaign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event__c</valueField>
            </filterItems>
            <filterItems>
                <field>Campaign.Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Required field for Lead Conversion</inlineHelpText>
        <label>Targeted Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Leads (Event)</relationshipLabel>
        <relationshipName>Lead_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>LeadToEvent__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Targeted SubExpo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Event__c</field>
                <operation>equals</operation>
                <valueField>SubExpo__c.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pi_ee_Campaign_Short_Desc__c</fullName>
        <label>Campaign Short Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pi_ee_Event_Code__c</fullName>
        <label>Pardot Event Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pi_ee_SubShowName__c</fullName>
        <label>Pardot Sub Show Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubExpo__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubShowName__c</fullName>
        <formula>SubShow__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShowName</label>
        <type>Text</type>
    </fields>
    <label>SubExpo</label>
    <nameField>
        <label>SubExpo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubExpos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ee_defaultLeadValues.cls
//This Class was redesigned 6/16/2020 by Tom Lopilato to address ee_UtilityValues

public class ee_defaultLeadValues {
    public static void defaultValues(Set<ID> leadIDs) {
        List<Lead> lstLeadsToBeUpdated = new List<Lead>();
        List<Event__c> events = new List<Event__c>();
        List<SubExpo__c> subExpo = new List<SubExpo__c>();
        List<Campaign> targetedCampaign = new List<Campaign>();

        Set<String> pardotEventCodes = new Set<String>();
        Set<String> pardotSubShowCodes = new Set<String>();
        Set<String> PardotInvalidSubShowCodes = new Set<String>();
        Set<String> PardotCampaignShortDescs = new Set<String>();
        Set<String> PardotInvalidCampaignShortDescs = new Set<String>();

        Set<Id> EventIds = new Set<Id>();

        List <Lead> lstLeads = [Select ID, pi_ee_Event_Code__c, Event__c, pi_ee_SubShowName__c, SubExpo__c, 
                                EE_Campaign__c, pi_ee_Campaign_Short_Desc__c, Description  from Lead where Id IN :leadIDs];
        
        
        map<string, Event__c> eventCodeToEventMap = new map<string, Event__c>();
        map<string, Event__c> showEventMap = new map<string, Event__c>();
        for(Event__c event : [select Id, Name,Event_Code__c,Event_ID__c,Event_Year__c,NextYear_Event_ID__c,NextYear_Event_ID__r.Stage_Date__c,Show_Code__c,Show__c, Stage_Date__c,Upcoming_Event_ID__c, Upcoming_Event_ID__r.Stage_Date__c from Event__c ORDER BY Stage_Date__c ASC Limit 49999 ]){
                if(event.Stage_Date__c >= System.Today() && !showEventMap.keySet().Contains(event.Show__c))
                    showEventMap.put(event.Show__c, event);
                eventCodeToEventMap.put(event.Event_Code__c, event);
                //if(pardotEventCodes.contains(event.Event_Code__c))
                //  events.add(event);
        }
        for(Lead ld: lstLeads){
            //pardotEventCodes.add(EE_UtilityValues.getActiveEventCode(ld.pi_ee_Event_Code__c));
            pardotEventCodes.add(EE_Task.getEventCode(eventCodeToEventMap, showEventMap,ld.pi_ee_Event_Code__c));

            pardotSubShowCodes.add(ld.pi_ee_SubShowName__c);
            PardotInvalidSubShowCodes.add(ld.pi_ee_SubShowName__c);

            PardotCampaignShortDescs.add(ld.pi_ee_Campaign_Short_Desc__c);
            PardotInvalidCampaignShortDescs.add(ld.pi_ee_Campaign_Short_Desc__c);
        }
        
        
        /*
        if(pardotEventCodes.size() > 0){
            events = [SELECT  Id, Event_Code__c,show__c from Event__c where Event_Code__c IN: pardotEventCodes];
        }
        */
        for(Event__c ev: eventCodeToEventMap.Values()){
            system.debug('----------------Entered -----------------------------');
            if(pardotEventCodes.Contains(ev.Event_Code__c)){
                EventIds.add(ev.Id);
                events.add(ev);
            }
        }
        system.debug('# EventIds : '+EventIds);
        if(pardotSubShowCodes.size() > 0 && EventIds.size() >0 ){
            subExpo = [SELECT Id,Name,Event__c,Event_Code__c, SubShowName__c from SubExpo__c where Event__c IN: EventIds and SubShowName__c IN: pardotSubShowCodes];
        }

        if(PardotCampaignShortDescs.size() > 0 && EventIds.size() >0 ){
            targetedCampaign = [SELECT Short_Description__c, Event__c, Event__r.Event_Code__c  FROM Campaign WHERE Event__c IN: EventIds and Short_Description__c IN:PardotCampaignShortDescs];
        }

        for(Lead l : lstLeads ) {
            System.debug('ee_defaultLeadValues::defaultValues:processing lead = ' + l);
            //String leadActiveEventCode = EE_UtilityValues.getActiveEventCode(l.pi_ee_Event_Code__c);
             String leadActiveEventCode = EE_Task.getEventCode(eventCodeToEventMap, showEventMap,l.pi_ee_Event_Code__c);
             system.debug('# leadActiveEventCode : '+leadActiveEventCode);
            for(Event__c e: events){
                System.debug('------------------Entered Events-----------------');

                //Update Targeted Event
                if( string.isNotBlank(leadActiveEventCode) && leadActiveEventCode == e.Event_Code__c) { //l.Event__c == NULL &&
                    l.Event__c = e.Id;

                    //Look for Targeted SubExpo
                    if(subExpo.size() > 0  && l.SubExpo__c == NULL) {
                        for(SubExpo__c subEx: subExpo) {
                            System.debug('ee_defaultLeadValues::defaultValues:SubExpo__c = ' + subEx.Id + '-' + subEx.Name); 
                            if(l.pi_ee_SubShowName__c == subEx.SubShowName__c && leadActiveEventCode == e.Event_Code__c ){
                                l.SubExpo__c = subEx.Id;
                                PardotInvalidSubShowCodes.remove(subEx.SubShowName__c);
                            }
                        }
                    }
                     
                    if(PardotInvalidSubShowCodes.size() > 0 && l.SubExpo__c == NULL) {
                        for(String invalidSE: PardotInvalidSubShowCodes) {
                            if(l.pi_ee_SubShowName__c != null && l.pi_ee_SubShowName__c == invalidSE && leadActiveEventCode == e.Event_Code__c ){
                                l.Description = 'Invalid SubShow Code is:' +l.pi_ee_SubShowName__c+'; \n';
                            }
                        }
                    }


                    //Lookup campaign
                    System.debug('ee_defaultLeadValues::defaultValues:EE_Campaign__c = ' + l.EE_Campaign__c + '-' + l.pi_ee_Campaign_Short_Desc__c + '- targetedCampaign = ' + targetedCampaign ); 
                          
                    if (targetedCampaign.size() > 0 && l.EE_Campaign__c == NULL) {

                        for(Campaign c: targetedCampaign) {    
                            if(String.isNotBlank(leadActiveEventCode) && leadActiveEventCode == e.Event_Code__c && leadActiveEventCode == c.Event__r.Event_Code__c && l.pi_ee_Campaign_Short_Desc__c == c.Short_Description__c ){
                                l.EE_Campaign__c = c.Id; 
                                System.debug('**************'+l.EE_Campaign__c);
                                PardotInvalidCampaignShortDescs.remove(c.Short_Description__c);
                            }
                        }
                    }

                    if(PardotInvalidCampaignShortDescs.size()> 0 && l.EE_Campaign__c == NULL){
                        for(String InvalidCampaingCode: PardotInvalidCampaignShortDescs) {    
                            if(l.pi_ee_Event_Code__c == e.Event_Code__c && l.pi_ee_Campaign_Short_Desc__c == InvalidCampaingCode ){
                                if(l.Description != null){
                                    l.Description += 'Invalid Campaign Short Description is:' +l.pi_ee_Campaign_Short_Desc__c+';';
                                }
                                else {
                                    l.Description = 'Invalid Campaign Short Description is:' +l.pi_ee_Campaign_Short_Desc__c+';';
                                }
                            }
                        }
                    }
                           
                    lstLeadsToBeUpdated.add(l);
                }
            }
                
            update lstLeadsToBeUpdated;
        }
    }
}