objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <formula>CASESAFEID(Campaign.Event__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <label>Promo Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Promo_Code__c</fullName>
        <label>Registration Promo Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/EE_Registration_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registration</label>
        <referenceTo>Registration__c</referenceTo>
        <relationshipLabel>EE_Registration_Queue</relationshipLabel>
        <relationshipName>EE_Registration_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EE_Registration_Queue</label>
    <nameField>
        <displayFormat>EERQ-{0}</displayFormat>
        <label>EE_Registration_Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EE_Registration_Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Registration__c.object
<CustomObject>
    <description>Contact's registration history from EventXL</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <label>Promo Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reg_Status__c</fullName>
        <label>Reg Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <label>Event Registration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_Job_SyncRegStatustoCampMemStatus.cls
public class EE_Job_SyncRegStatustoCampMemStatus implements Database.Batchable<sObject>{
    private string query;

    public EE_Job_SyncRegStatustoCampMemStatus(){
        query = 'Select Id, Registration__c from EE_Registration_Queue__c Order by LastModifiedDate DESC limit 50000';
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        Map<Id,Registration__c> regMap = new Map<Id,Registration__c>();
        Set<Id> regcontIdSet = new Set<Id>();
        Set<Id> regeveIdSet = new Set<Id>();
        List<CampaignMember> cmList = new List<CampaignMember>();
        Set<CampaignMember> campMemUpdateSet = new Set<CampaignMember>();
        List<Registration__c> updateRegList = new List<Registration__c>();
        
        Set<Id> regIdsSet = new Set<Id>();
        List<EE_Registration_Queue__c> reqQueueIdsList = new List<EE_Registration_Queue__c>();
        for(EE_Registration_Queue__c regque: (List<EE_Registration_Queue__c>) scope){
            regIdsSet.add(regque.Registration__c);
            reqQueueIdsList.add(regque);
        }
        
        List<Registration__c> regList = [Select Id, Contact__c, Event__c, Promo_Code__c, Reg_Status__c from Registration__c Where Id IN: regIdsSet];
        for(Registration__c reg: regList){
            regMap.put(reg.Id,reg);
            system.debug('regMap'+regMap);
            regcontIdSet.add(reg.Contact__c);
            regeveIdSet.add(reg.Event__c);
        }

        cmList = [Select Id, ContactId, Campaign.Event__c, Promo_Code__c, Status from CampaignMember where ContactId IN: regcontIdSet AND Campaign.Event__c IN: regeveIdSet AND (Status != 'Registered' OR Status != 'Cancelled' )];
        system.debug('cmList'+cmList);
        
        for(ID reg: regMap.keyset()){
            for(CampaignMember campMem: cmList){
                if(regMap.get(reg).Contact__c == campMem.ContactId && regMap.get(reg).Event__c == campMem.Campaign.Event__c && regMap.get(reg).Reg_Status__c == 'Cancelled'){
                    CampaignMember campaignmem = new CampaignMember();
                    campaignmem.Id = campMem.Id;
                    campaignmem.Status = regMap.get(reg).Reg_Status__c;
                    campaignmem.Registration_Promo_Code__c = regMap.get(reg).Promo_Code__c;
                    campMemUpdateSet.add(campaignmem);

                } 
                
                else if(regMap.get(reg).Contact__c == campMem.ContactId && regMap.get(reg).Event__c == campMem.Campaign.Event__c && regMap.get(reg).Reg_Status__c != 'Cancelled'){
                    CampaignMember campaignmem1 = new CampaignMember();
                    campaignmem1.Id = campMem.Id;
                    campaignmem1.Status = 'Registered';
                    campaignmem1.Registration_Promo_Code__c = regMap.get(reg).Promo_Code__c;
                    campMemUpdateSet.add(campaignmem1);

                }
            }
        }
        if(campMemUpdateSet.size()>0){
            list<CampaignMember> campMemUpdateList = new List<CampaignMember>();
            campMemUpdateList.addAll(campMemUpdateSet);
            update campMemUpdateList;  
            
            if(campMemUpdateList.size()>0 && reqQueueIdsList.size()>0){
                delete reqQueueIdsList;
            }  
        }


    }
    public void finish(Database.BatchableContext BC){
        if(!Test.IsRunningTest()){
            EE_Job_SyncRegStatustoCampMemStatus b = new EE_Job_SyncRegStatustoCampMemStatus(); 
            System.scheduleBatch(b, 'EE_Job_SyncRegStatustoCampMemStatus', 60, 100);
        }      
    }       
}