objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Details_By_Show__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Details By Show</relationshipLabel>
        <relationshipName>Contact_Details_By_Show</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contact Details By Show</relationshipLabel>
        <relationshipName>Contact_Details_By_Show</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Contact Details By Show</label>
    <nameField>
        <displayFormat>CDS-{0}</displayFormat>
        <label>Contact Details By Show Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Details By Show</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Segment__c.object
<CustomObject>
    <description>Use to tag contacts (label, list)  by show/event</description>
    <fields>
        <fullName>Contact_Details_By_Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Details By Show</label>
        <referenceTo>Contact_Details_By_Show__c</referenceTo>
        <relationshipLabel>Contact Segments</relationshipLabel>
        <relationshipName>Contact_Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Segments</relationshipLabel>
        <relationshipName>Contact_Segments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Contact Segments</relationshipLabel>
        <relationshipName>Contact_Segments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Segment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Contact Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Winback</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Current Exhibitor</fullName>
                </value>
                <value>
                    <fullName>Current Attendee</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Persona</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EE_CreateConDetailsbyShowTest.cls
@isTest
public class EE_CreateConDetailsbyShowTest {

    static testmethod void EE_CreateConDetailsbyShowTest() {
        date myDate = date.today();
        Date newDate = mydate.addDays(2);
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;

        // Create contacts
        Contact ct1 = new Contact();
        ct1.FirstName = 'Emerald';
        ct1.LastName = 'Test';
        ct1.Email = 'EmeraldTest@ee.com';
        ct1.AccountId = account.Id;
        Insert ct1;

        // Create contacts
        Contact ct2 = new Contact();
        ct2.FirstName = 'Emerald';
        ct2.LastName = 'Test';
        ct2.Email = 'EmeraldTest@ee.com';
        ct2.AccountId = account.Id;
        Insert ct2;

        //Create Show 
		Show__c show = new Show__c();
		show.Name='Test Show';
		show.Brand__c='TBrand';
		show.Market__c='TMarket';
		show.Rule_Set__c='ASD_SB';
		show.Segment__c='TSegment';
		show.Show_Code__c='TShowCode';      
		show.Show_Group__c='ShowGroup';
		show.ShowID__c=12345;
        insert show;
        
        //create Segment
        Segment__c segment = new Segment__c();
        segment.Name ='Test segment';
        segment.Show__c = show.id;
        segment.Type__c = 'Renewal';
        insert segment;

        //create Segment
        Segment__c segment1 = new Segment__c();
        segment1.Name ='Test segment1';
        segment1.Show__c = show.id;
        segment1.Type__c = 'Renewal';
        insert segment1;

        //Create contact details by Show
        Contact_Details_By_Show__c cds = new Contact_Details_By_Show__c();
        cds.Contact__c = ct1.id;
        cds.Show__c = show.id;
        insert cds;

        //Create contact Segment
        Contact_Segment__c conseg = new Contact_Segment__c();
        conseg.Contact__c= ct1.id;
        conseg.Segment__c= segment.id;

        //Create contact Segment
        Contact_Segment__c conseg1 = new Contact_Segment__c();
        conseg1.Contact__c= ct2.id;
        conseg1.Segment__c= segment1.id;


        test.startTest();
        insert conseg;
        insert conseg1;
        test.stopTest();
    }
}