objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hygiene_Status__c</fullName>
        <label>Hygiene Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Hygiened Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Undeliverable</fullName>
                </value>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>GDPR Do Not Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>a2z_Contact_ID__c</fullName>
        <description>a2z contact id</description>
        <externalId>true</externalId>
        <label>a2z Contact ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_ContactTgrHandlerTest.cls
@isTest
public with sharing class EE_ContactTgrHandlerTest {
    
    @isTest
    static void EE_ContactTgrHandlerTest() {
        date myDate = date.today();
        Date newDate = mydate.addDays(2);

        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;

        // Create two contacts
        Contact ct1 = new Contact();
        ct1.FirstName = 'Emerald';
        ct1.LastName = 'Test';
        ct1.Email = 'EmeraldTest@ee.com';
        ct1.AccountId = account.Id;
        Insert ct1;  

        Contact ct2 = new Contact();
        ct2.FirstName = 'Emerald2';
        ct2.LastName = 'Test2';
        ct2.Email = 'EmeraldTest2@ee.com';
        ct2.AccountId = account.Id;
        ct2.Hygiene_Status__c= 'Undeliverable';
        ct2.EmailBouncedReason ='test';
        Insert ct2;  

        List<Contact> ConList = new List<Contact>();
        contact tempcon1 =new contact();
        tempcon1.Id = ct1.Id;
        tempcon1.a2z_Contact_ID__c='12345';
        tempcon1.Email='con1ee123@test.com';
        ConList.add(tempcon1);

        contact tempcon2 =new contact();
        tempcon2.Id = ct2.Id;
        tempcon2.Email='con2ee123@test.com';
        ConList.add(tempcon2);
    
        
        test.startTest();
        update ConList;
        test.stopTest();


    }
}