objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityContactRole.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <formula>CASESAFEID( Opportunity.Event__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Show_Account_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles by Show</relationshipLabel>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ContactRoles__c</fullName>
        <label>Contact Roles</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A2Z Invoice Contact</fullName>
                </value>
                <value>
                    <fullName>Advertising contact</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Contract Contact</fullName>
                    <default>true</default>
                    <label>Contract Contact</label>
                </value>
                <value>
                    <fullName>Contract Contact (Secondary)</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Decorator</fullName>
                </value>
                <value>
                    <fullName>Directory contact</fullName>
                </value>
                <value>
                    <fullName>Distributor Representative</fullName>
                </value>
                <value>
                    <fullName>Exhibitor kit recipient</fullName>
                </value>
                <value>
                    <fullName>Marketing Contact</fullName>
                </value>
                <value>
                    <fullName>Only contact</fullName>
                </value>
                <value>
                    <fullName>Onsite contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Sponsorship contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles by Show</relationshipLabel>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Show_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role by Show</label>
    <nameField>
        <displayFormat>S{0000}</displayFormat>
        <label>Show Account Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles by Show</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EE_AddContactRoleByShow.cls
public class EE_AddContactRoleByShow {
    // 06/12/19 Spoorthy Teegala - addContactRoleByShow - This method is used for adding/creating 
    // Opportunity Contact Roles from Contact Role by Show recrds from associated Account for a given opporunity
    public void addContactRoleByShow(Map<id,Opportunity> newOppMap){
        
        List<Opportunity> oppList = new List<Opportunity>();
        Set<Id> AccIdSet = new Set<Id>();
        Map<Id, Opportunity> oppAccMap = new Map<Id, Opportunity>();
        List<Show_Account_Contact__c> CRBSList = new List<Show_Account_Contact__c>();
        List<OpportunityContactRole>  OppCRList = new List<OpportunityContactRole>();
        
        oppList = [Select Id, AccountID,Event__r.Show__r.Name from Opportunity where Id IN :newOppMap.keySet()];
        
        for(Opportunity opp :oppList ){
                oppAccMap.put(opp.ID, opp); 
                AccIdSet.add(opp.AccountID);      
        }
        
        List<String> ValidCRbyShowList = new List<String>{'A2Z Invoice Contact', 'Contract Contact', 'Marketing Contact', 'Sales Contact','Contract Contact (Secondary)', 'Sponsorship contact'};
        CRBSList = [select id, Account__c, Contact__c, ContactRoles__c,Show__r.Name from Show_Account_Contact__c where Account__c IN: AccIdSet and ContactRoles__c IN: ValidCRbyShowList]; 
        
        if(CRBSList.size() > 0){
            for(id OppId: oppAccMap.keyset()) {
                for(Show_Account_Contact__c crbs: CRBSList ){
                    if(crbs.Account__c == oppAccMap.get(OppId).AccountID && crbs.Show__r.Name == oppAccMap.get(OppId).Event__r.Show__r.Name) {
                        OpportunityContactRole ocr= new OpportunityContactRole();
                        ocr.ContactId = crbs.Contact__c;
                        ocr.OpportunityId = OppId;
                        ocr.Role = crbs.ContactRoles__c;
                        OppCRList.add(ocr);
                    }
                }
            }
            
            insert OppCRList;
        }
    }
}