objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hygiene_Status__c</fullName>
        <label>Hygiene Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Hygiened Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Undeliverable</fullName>
                </value>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>GDPR Do Not Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>a2z_Contact_ID__c</fullName>
        <description>a2z contact id</description>
        <externalId>true</externalId>
        <label>a2z Contact ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EE_ContactTgrHandler.cls
public without sharing class EE_ContactTgrHandler {
    public void UpdateContactEmailHygiene(Map<Id,Contact> newContMap, Map<Id,Contact> oldContMap ) {
       
        List<Contact> ConList = new List<Contact>();
        
        if((newContMap.Values()).size() > 0){
            for(Contact Cont: newContMap.Values()){
                Boolean Entered = False;
                if(Cont.a2z_Contact_ID__c != Null){
                    cont.Hygiene_Status__c= 'Customer';
                    ConList.add(cont);
                    Entered = True;
                    System.debug('***** Entered 1 ****');
                }
                
                if( Entered == False && Cont.Hygiene_Status__c == 'Undeliverable' && newContMap.get(Cont.Id).Email != oldContMap.get(Cont.Id).Email){
                    System.debug('***** Entered 2 ****');
                    
                    cont.Hygiene_Status__c = 'Prospect';
                    cont.EmailBouncedDate = Null;
                    cont.EmailBouncedReason = Null;
                    ConList.add(cont);
                }

            }
        }
    }
}