objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <inlineHelpText>Edge reference ID</inlineHelpText>
        <label>ContactGUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Segment__c.object
<CustomObject>
    <description>Use to tag contacts (label, list)  by show/event</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Segments</relationshipLabel>
        <relationshipName>Contact_Segments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Contact Segments</relationshipLabel>
        <relationshipName>Contact_Segments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Segment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Contact Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Show__r.Brand__c</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipName>Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Winback</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Current Exhibitor</fullName>
                </value>
                <value>
                    <fullName>Current Attendee</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Persona</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowID__c</fullName>
        <label>ShowID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Group__c</fullName>
        <label>Show Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EE_ContactSegmentTgrTest.cls
@isTest
public class EE_ContactSegmentTgrTest {
    static testmethod void EE_ContactSegmentTgrTest() {
        //Account
        Account account = new Account();
        account.Name='Test Account';
        insert account;

        // Create contacts
        Contact ct1 = new Contact();
        ct1.FirstName = 'Emerald';
        ct1.LastName = 'Test';
        ct1.Email = 'EmeraldTest@ee.com';
        ct1.AccountId = account.Id;
        ct1.ContactGUID__c = 'TEST-TEST-TEST20';
        insert ct1;

        
        //Create Show 
        Show__c show = new Show__c();
        show.Name='Test Show';
        show.Brand__c='TBrand';
        show.Market__c='TMarket';
        show.Rule_Set__c='ASD_SB';
        show.Segment__c='TSegment';
        show.Show_Code__c='TShowCode';      
        show.Show_Group__c='ShowGroup';
        show.ShowID__c=12345;
        insert show;

        //Create contact segment
        Segment__c segment = new Segment__c();
        segment.Name ='Test segment1';
        segment.Show__c = show.id;
        segment.Type__c = 'Renewal';
        insert segment;

        //Create contact segment
        Segment__c segment1 = new Segment__c();
        segment1.Name ='Test segment';
        segment1.Show__c = show.id;
        segment1.Type__c = 'Renewal';
        insert segment1;

        //Create contact Segment
        Contact_Segment__c conseg = new Contact_Segment__c();
        conseg.Contact__c= ct1.id;
        conseg.Segment__c= segment.id;
        insert conseg;

        test.startTest();

        try{
            //Create contact Segment
            Contact_Segment__c conseg1 = new Contact_Segment__c();
            conseg1.Contact__c= ct1.id;
            conseg1.Segment__c= segment.id;
            insert conseg1;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Contact Segment Record already exists')? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        try{
            //Update contact Segment
            Contact_Segment__c conseg2 = new Contact_Segment__c();
            conseg2.Id = conseg.id;
            conseg2.Segment__c = segment1.id;
            Update conseg2;
        }
        catch(Exception e1){
            Boolean expectedExceptionThrown =  e1.getMessage().contains('Contact Segment Record already exists')? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        test.stopTest();
             
    }
}