objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <label>Event Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_ID__c</fullName>
        <label>Event ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Year__c</fullName>
        <label>Event Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NextYear_Event_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Year Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Next Year Event</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Code__c</fullName>
        <formula>Show__r.Show_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Date__c</fullName>
        <label>Stage Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Upcoming_Event_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Up Coming Event (Event)</relationshipLabel>
        <relationshipName>Upcoming_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Show_Code__c</fullName>
        <label>Show Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EE_UtilityValues.cls
// Spoorthy Teegala - This Class is used for storing all the static variables
public Class EE_UtilityValues {
    public static String RT_AccountName = 'Account Name';
    public static String RT_BillingState = 'Billing State';
    public static String RT_Show = 'Show';
    public static String RT_SubShow = 'SubShow';
    public static String RT_ANBS = 'Account Name & Billing State';
    public static String International = 'International';
    public static String Country_US = 'US';
    
    
    public static Id getActiveEventID (String EventCode){
        
        Id ActiveEventId = null;
        List<Event__c> nextEventList = new List<Event__c>();
        List<Event__c> currentEvents = [select Id, Name,Event_Code__c,Event_ID__c,Event_Year__c,NextYear_Event_ID__c,NextYear_Event_ID__r.Stage_Date__c,Show_Code__c,Show__c,Stage_Date__c,Upcoming_Event_ID__c, Upcoming_Event_ID__r.Stage_Date__c from Event__c where Event_Code__c =: EventCode ];
        
        //
        if(currentEvents.size() >0 && currentEvents[0].Stage_Date__c < date.Today() ) {
             
            nextEventList =  [select Id, Name,Event_Code__c,Event_ID__c,Event_Year__c,NextYear_Event_ID__c,NextYear_Event_ID__r.Stage_Date__c,Show_Code__c,Show__c, Stage_Date__c,Upcoming_Event_ID__c, Upcoming_Event_ID__r.Stage_Date__c from Event__c where Show__c =: currentEvents[0].Show__c and Stage_Date__c >= Today ORDER BY Stage_Date__c ASC Limit 1  ]; //    
        }
        
        if(nextEventList.size() > 0) {
            ActiveEventId = nextEventList[0].Id;
        }
        else{
            ActiveEventId = currentEvents[0].Id;
        }

        return ActiveEventId;
    }

    public static String getActiveEventCode (String EventCode){
        
        String ActiveEventCode = '';
        List<Event__c> nextEventList = new List<Event__c>();
        List<Event__c> currentEvents = [select Id, Name,Event_Code__c,Event_ID__c,Event_Year__c,NextYear_Event_ID__c,NextYear_Event_ID__r.Stage_Date__c,Show_Code__c,Show__c,Stage_Date__c,Upcoming_Event_ID__c, Upcoming_Event_ID__r.Stage_Date__c from Event__c where Event_Code__c =: EventCode ];
        
        if(currentEvents.size() >0 && currentEvents[0].Stage_Date__c < date.today()) {
             
            nextEventList =  [select Id, Name,Event_Code__c,Event_ID__c,Event_Year__c,NextYear_Event_ID__c,NextYear_Event_ID__r.Stage_Date__c,Show_Code__c,Show__c, Stage_Date__c,Upcoming_Event_ID__c, Upcoming_Event_ID__r.Stage_Date__c from Event__c where Show__c =: currentEvents[0].Show__c and Stage_Date__c >= Today ORDER BY Stage_Date__c ASC Limit 1  ]; //    
        }
        
        if(nextEventList.size() > 0) {
            ActiveEventCode = nextEventList[0].Event_Code__c;
        }
        else{
            ActiveEventCode = EventCode;
        }

        return ActiveEventCode;
    } 
    
}