objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <label>Event Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AccountNameFirstChar__c</fullName>
        <formula>IF(
BEGINS(upper(Company), "THE "),
Upper(RIGHT(LEFT(Company,5),1)),
Upper(LEFT(Company,1))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name First Char</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryandStateCode__c</fullName>
        <formula>(BLANKVALUE(TEXT(CountryCode),'') + IF( ISPICKVAL(StateCode , ''), '', '-') +BLANKVALUE(TEXT(StateCode),''))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BillingCountryandStateCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(CountryCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State_Code__c</fullName>
        <formula>BLANKVALUE( NULLVALUE(TEXT(StateCode),'NULL'),'NULL')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing State Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Required field for Lead Conversion</inlineHelpText>
        <label>Targeted Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Leads (Event)</relationshipLabel>
        <relationshipName>Lead_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <formula>BLANKVALUE(SubExpo__r.SubShow__r.Rule_Set__c,Event__r.Show__r.Rule_Set__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rule Set</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>LeadToEvent__r.Show__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubExpo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Targeted SubExpo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Event__c</field>
                <operation>equals</operation>
                <valueField>SubExpo__c.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubExpo__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Rule_ID__c</fullName>
        <description>Territory Rule ID Applied</description>
        <label>Territory Rule ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pi_ee_Event_Code__c</fullName>
        <label>Pardot Event Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>should_Ignore_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If check, opportunity owner won't be set by auto-assignment rule.</description>
        <label>Should Ignore Assignment Rule?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SubExpo__c.object
<CustomObject>
    <fields>
        <fullName>Event_Code__c</fullName>
        <formula>Event__r.Event_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>SubExpos</relationshipLabel>
        <relationshipName>SubExpos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <formula>Event__r.Show__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubShowName__c</fullName>
        <formula>SubShow__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubShowName</label>
        <type>Text</type>
    </fields>
    <label>SubExpo</label>
    <nameField>
        <label>SubExpo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubExpos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Rule__c.object
<CustomObject>
    <fields>
        <fullName>IsActiveUser__c</fullName>
        <formula>OpportunityOwner__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsActiveUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key1__c</fullName>
        <label>Key 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key2__c</fullName>
        <label>Key 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Territory_Rule_ID__c &amp; ' - ' &amp; OpportunityOwner__r.FirstName &amp;' ' &amp;  OpportunityOwner__r.LastName &amp; ' - ' &amp;  Key1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Rule_ID__c</fullName>
        <label>Territory Rule ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Rule_Type__c</fullName>
        <label>Territory Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Name</fullName>
                </value>
                <value>
                    <fullName>Billing State</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>SubShow</fullName>
                </value>
                <value>
                    <fullName>Account Name &amp; Billing State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory Rule</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ee_defaultLeadOwner.cls
public class ee_defaultLeadOwner {
     
     public static void defaultLeadOwner(Set<ID> leadIDs){
          String RT_AccountName = EE_UtilityValues.RT_AccountName;
          String RT_BillingState = EE_UtilityValues.RT_BillingState;
          String RT_Show = EE_UtilityValues.RT_Show;
          String RT_SubShow = EE_UtilityValues.RT_SubShow;
          String RT_ANBS = EE_UtilityValues.RT_ANBS;
          String International = EE_UtilityValues.International;
          String Country_US = EE_UtilityValues.Country_US;
          //new changes to the territory rule assignment will assign the lead owner based on the territory rule name in ASC order
          List <Lead>lstLeadsToBeUpdated = new List<Lead>();
          Set<id> LeadIDSet = new Set<id>();
        
          List <Lead> lstLeads = new List<Lead>([Select ID,Company, Name,Email,AccountNameFirstChar__c,BillingCountryandStateCode__c, Billing_Country_Code__c,Billing_State_Code__c,Rule_Set__c, Event__r.Show__r.Name, Event__r.Show__r.OwnerId, Event__r.Show__r.Owner.IsActive, SubExpo__r.SubShowName__c  from Lead where Id IN :leadIDs
                                                and Should_Ignore_Assignment_Rule__c = FALSE
                                                and Rule_Set__c != 'Disabled' 
                                                and Rule_Set__c != NULL
                                                and Rule_Set__c != '']
                                                );
  
          Set<String> TerritoryRulesSet = new Set<String>();
          for(Lead l : lstLeads ) {
               TerritoryRulesSet.add(l.Rule_Set__c);
          }
          System.debug('ee_defaultLeadOwer::defaultLeadOwner:TerritoryRulesSet = ' + TerritoryRulesSet);             
         
          List<Territory_Rule__c> TerritoryRules  = new List<Territory_Rule__c>([Select Name__c,Key1__c,Key2__c, OpportunityOwner__c,Rule_Set__c,Territory_Rule_Type__c, Territory_Rule_ID__c from Territory_Rule__c where Rule_Set__c   IN  : TerritoryRulesSet and IsActiveUser__c = TRUE order by Name__c ASC]);
          
          System.debug('ee_defaultLeadOwer::defaultLeadOwner:found rules = ' + TerritoryRules);
         
          for(Lead l : lstLeads ) {
               
               
               if(TerritoryRules.size() >0){
                    for(Territory_Rule__c tr: TerritoryRules){
                         if(LeadIDSet.contains(l.id))
                              continue;
                         //Account Name
                         if(l.Rule_Set__c == tr.Rule_Set__c){   
                              if(tr.Territory_Rule_Type__c == RT_AccountName ){
                                   if(tr.Key1__c.contains(l.AccountNameFirstChar__c) ){                             
                                        l.OwnerId=tr.OpportunityOwner__c;
                                        l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                                        lstLeadsToBeUpdated.add(l);
                                        LeadIDSet.add(l.id);
                                        System.debug('@@@@@@@@@@@@@@@@@@@@@' +l);
                                        continue;
                                   }
                              }     
                         }
                         
                         //Billing State
                         if(tr.Territory_Rule_Type__c == RT_BillingState){
                              if(String.IsNotBlank(tr.Key1__c) && tr.Key1__c.contains(l.Billing_Country_Code__c)){
                                   if(tr.Key2__c=='*') {
                                   // Territory Rules is for the entire country
                                   l.OwnerId=tr.OpportunityOwner__c;
                                   l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                                   lstLeadsToBeUpdated.add(l);
                                   LeadIDSet.add(l.id);
                                   System.debug('@@@@@@@@@@@@@@@@@@@@@11111' +l);
                                   continue;
                                   
                                   } else if ( tr.Key2__c.contains(l.Billing_State_Code__c)) {
                                   //Country and State match territory rule
                                   l.OwnerId=tr.OpportunityOwner__c;
                                   l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                                   lstLeadsToBeUpdated.add(l);
                                   LeadIDSet.add(l.id);
                                   System.debug('@@@@@@@@@@@@@@@@@@@@@2222222' +l);
                                   continue;
                                   }
                              } 
                              system.debug('############'+l.Billing_Country_Code__c);
                              system.debug('44444444444444'+tr.Key2__c);
                              if(tr.Key1__c== International  && String.IsNotBlank(tr.Key2__c) && l.Billing_Country_Code__c != 'NULL' && !tr.Key2__c.contains(l.Billing_Country_Code__c) && l.Billing_Country_Code__c!= Country_US) {
                                   //International rules except US and whatever countries listed in Key2__c.
                                   //Some times show don't consider Canada as part of international countries                 
                                   l.OwnerId=tr.OpportunityOwner__c;
                                   l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                                   lstLeadsToBeUpdated.add(l);
                                   LeadIDSet.add(l.id);
                                   System.debug('@@@@@@@@@@@@@@@@@@@@@333333' +l);
                                   continue;                                            
                              }
                         }
                    
                         //Show
                         if(tr.Territory_Rule_Type__c == RT_Show && tr.Key1__c.contains(l.Event__r.Show__r.Name)){
                              l.OwnerId=tr.OpportunityOwner__c;
                              lstLeadsToBeUpdated.add(l);
                              LeadIDSet.add(l.id);
                              System.debug('@@@@@@@@@@@@@@@@@@@@@44444444444444' +l);
                              continue;                                            
                         }
                    
                         //Sub Show
                         if(tr.Territory_Rule_Type__c == RT_SubShow && l.SubExpo__r.SubShowName__c != null && tr.Key2__c.contains(l.SubExpo__r.SubShowName__c)){
                              l.OwnerId=tr.OpportunityOwner__c;
                              l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                              lstLeadsToBeUpdated.add(l);
                              LeadIDSet.add(l.id);
                              System.debug('@@@@@@@@@@@@@@@@@@@@@5555' +l);
                              continue;                                            
                         }
                         system.debug('@@@@@@@@@@@@@@@@@l.BillingCountryandStateCode__c'+l.BillingCountryandStateCode__c);
                         //Account Name and Billing State
                         if(tr.Territory_Rule_Type__c == RT_ANBS && tr.Key1__c.contains(l.AccountNameFirstChar__c) && !string.isBlank(l.BillingCountryandStateCode__c) && tr.Key2__c.contains(l.BillingCountryandStateCode__c)){ 
                              l.OwnerId=tr.OpportunityOwner__c;
                              l.Territory_Rule_ID__c = tr.Territory_Rule_ID__c;
                              lstLeadsToBeUpdated.add(l);
                              LeadIDSet.add(l.id);

                              System.debug('@@@@@@@@@@@@@@@@@@@@@66666' +l);
                              continue;                                            
                         }                   
                    }
               }

               if(TerritoryRules.size() == 0 || !LeadIDSet.contains(l.id)){
                    if(l.Event__r.Show__r.Owner.IsActive == True){
                         l.OwnerId = l.Event__r.Show__r.OwnerId;
                         lstLeadsToBeUpdated.add(l);
                         LeadIDSet.add(l.id);
                    } 
               }
          }
          //Update Leads with udpated owner

          
          update lstLeadsToBeUpdated;
          System.debug('ee_defaultLeadOwer::defaultLeadOwner:lstLeadsToBeUpdated = '+lstLeadsToBeUpdated);
     }

     // Spoorthy Teegala - addLeadsToQueue() is used for assigning leads to Sales Rep Queue if Event Code is not Valid
     public static void addLeadsToQueue(List<Lead> newleadsList){
          
          Set<String> pLEventCodes = new Set<String>();
          Set<String> InvalidEventCodes = new Set<String>();

          //Group SalesOpsQueue = [Select Id from Group where Type = 'Queue' AND Name = 'Sales Ops' LIMIT 1];

          for(Lead nl: newleadsList){
               if(nl.pi_ee_Event_Code__c != ''){
                    pLEventCodes.add(nl.pi_ee_Event_Code__c);
               }
          }

          if(pLEventCodes.size()> 0){
               List <Event__c> pardotEventList =[Select id,Event_code__c from Event__c where Event_code__c IN: pLEventCodes];
               
               if(pardotEventList.size()>0){
                    InvalidEventCodes.addAll(pLEventCodes);
                    for(Event__c e: pardotEventList){
                         if(pLEventCodes.contains(e.Event_code__c) ){
                              //Removing valid event codes to filterout invalid event codes
                              InvalidEventCodes.remove(e.Event_code__c);
                         }
                    }  
               }
               if(pardotEventList.size() == 0){
                    // add leads event codes directly to invalid code set if query on event codes returns 0 items
                    InvalidEventCodes.addAll(pLEventCodes);
               }
          }

          if(InvalidEventCodes.size() > 0){
               for(Lead l: newleadsList){
                    for(String invalidCode:InvalidEventCodes){
                         if(l.pi_ee_Event_Code__c == invalidCode){
                              //assigning the lead owner as Sales Rep queue if a given lead as invalid pardot event code
                              //l.OwnerId = SalesOpsQueue.ID;
                              l.Description = 'Invalid Event Code is:' +l.pi_ee_Event_Code__c;
                         }
                    }
               }
          }
     }

}